otus_cpp_print_ip: Queue< E > Class Template Reference
Queue< E > Class Template Reference
#include <sample3-inl.h>
Public Member Functions
Queue ()
~Queue ()
void Clear ()
size_t Size () const
QueueNode< E > * Head ()
const QueueNode< E > * Head () const
QueueNode< E > * Last ()
const QueueNode< E > * Last () const
void Enqueue (const E &element)
E * Dequeue ()
template<typename F >
Queue * Map (F function) const
Private Member Functions
Queue (const Queue &)
const Queue & operator= (const Queue &)
Private Attributes
QueueNode< E > * head_
QueueNode< E > * last_
size_t size_
Detailed Description
template<typename E>
class Queue< E >
Definition at line 42 of file sample3-inl.h.
Constructor & Destructor Documentation
Queue() [1/2]
template<typename E > Queue< E >::Queue () inline
Definition at line 76 of file sample3-inl.h.
 : head_(nullptr), last_(nullptr), size_(0) {}
Referenced by Queue< E >::Map().
~Queue()
template<typename E > Queue< E >::~Queue () inline
Definition at line 79 of file sample3-inl.h.
 { Clear(); }
References Queue< E >::Clear().
Queue() [2/2]
template<typename E > Queue< E >::Queue (const Queue< E > &) private
Member Function Documentation
Clear()
template<typename E > void Queue< E >::Clear () inline
Definition at line 82 of file sample3-inl.h.
                {
     if (size_ > 0) {
       // 1. Deletes every node.
       QueueNode<E>* node = head_;
       QueueNode<E>* next = node->next();
       for (; ;) {
         delete node;
         node = next;
         if (node == nullptr) break;
         next = node->next();
       }
       // 2. Resets the member variables.
       head_ = last_ = nullptr;
       size_ = 0;
     }
   }
References Queue< E >::head_, Queue< E >::last_, QueueNode< E >::next(), and Queue< E >::size_.
Referenced by Queue< E >::~Queue().
Dequeue()
template<typename E > E* Queue< E >::Dequeue () inline
Definition at line 130 of file sample3-inl.h.
                {
     if (size_ == 0) {
       return nullptr;
     }
     const QueueNode<E>* const old_head = head_;
     head_ = head_->next_;
     size_--;
     if (size_ == 0) {
       last_ = nullptr;
     }
     E* element = new E(old_head->element());
     delete old_head;
     return element;
   }
References QueueNode< E >::element(), Queue< E >::head_, Queue< E >::last_, and Queue< E >::size_.
Enqueue()
template<typename E > void Queue< E >::Enqueue (const E & element) inline
Definition at line 115 of file sample3-inl.h.
{
     QueueNode<E>* new_node = new QueueNode<E>(element);
     if (size_ == 0) {
       head_ = last_ = new_node;
       size_ = 1;
     } else {
       last_->next_ = new_node;
       last_ = new_node;
       size_++;
     }
   }
References Queue< E >::head_, Queue< E >::last_, and Queue< E >::size_.
Referenced by Queue< E >::Map().
Head() [1/2]
template<typename E > QueueNode<E>* Queue< E >::Head () inline
Definition at line 104 of file sample3-inl.h.
 { return head_; }
References Queue< E >::head_.
Head() [2/2]
template<typename E > const QueueNode<E>* Queue< E >::Head () const inline
Definition at line 105 of file sample3-inl.h.
 { return head_; }
References Queue< E >::head_.
Last() [1/2]
template<typename E > QueueNode<E>* Queue< E >::Last () inline
Definition at line 108 of file sample3-inl.h.
 { return last_; }
References Queue< E >::last_.
Last() [2/2]
template<typename E > const QueueNode<E>* Queue< E >::Last () const inline
Definition at line 109 of file sample3-inl.h.
 { return last_; }
References Queue< E >::last_.
Map()
template<typename E > template<typename F > Queue* Queue< E >::Map (F function) const inline
Definition at line 152 of file sample3-inl.h.
{
     Queue* new_queue = new Queue();
     for (const QueueNode<E>* node = head_; node != nullptr;
          node = node->next_) {
       new_queue->Enqueue(function(node->element()));
     }
     return new_queue;
   }
References Queue< E >::Enqueue(), Queue< E >::head_, and Queue< E >::Queue().
operator=()
template<typename E > const Queue& Queue< E >::operator= (const Queue< E > &) private
Size()
template<typename E > size_t Queue< E >::Size () const inline
Definition at line 101 of file sample3-inl.h.
 { return size_; }
References Queue< E >::size_.
Member Data Documentation
head_
template<typename E > QueueNode<E>* Queue< E >::head_ private
Definition at line 163 of file sample3-inl.h.
Referenced by Queue< E >::Clear(), Queue< E >::Dequeue(), Queue< E >::Enqueue(), Queue< E >::Head(), and Queue< E >::Map().
last_
template<typename E > QueueNode<E>* Queue< E >::last_ private
Definition at line 164 of file sample3-inl.h.
Referenced by Queue< E >::Clear(), Queue< E >::Dequeue(), Queue< E >::Enqueue(), and Queue< E >::Last().
size_
template<typename E > size_t Queue< E >::size_ private
Definition at line 165 of file sample3-inl.h.
Referenced by Queue< E >::Clear(), Queue< E >::Dequeue(), Queue< E >::Enqueue(), and Queue< E >::Size().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/samples/sample3-inl.h