otus_cpp_print_ip: testing::internal::ParameterizedTestSuiteRegistry Class Reference
testing::internal::ParameterizedTestSuiteRegistry Class Reference
#include <gtest-param-util.h>
Public Member Functions
ParameterizedTestSuiteRegistry ()
~ParameterizedTestSuiteRegistry ()
template<class TestSuite >
ParameterizedTestSuiteInfo< TestSuite > * GetTestSuitePatternHolder (const char *test_suite_name, CodeLocation code_location)
void RegisterTests ()
template<class TestCase >
ParameterizedTestCaseInfo< TestCase > * GetTestCasePatternHolder (const char *test_case_name, CodeLocation code_location)
Private Types
using TestSuiteInfoContainer = ::std::vector< ParameterizedTestSuiteInfoBase * >
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ParameterizedTestSuiteRegistry)
Private Attributes
TestSuiteInfoContainer test_suite_infos_
Detailed Description
Definition at line 684 of file gtest-param-util.h.
Member Typedef Documentation
TestSuiteInfoContainer
using testing::internal::ParameterizedTestSuiteRegistry::TestSuiteInfoContainer = ::std::vector<ParameterizedTestSuiteInfoBase*> private
Definition at line 740 of file gtest-param-util.h.
Constructor & Destructor Documentation
ParameterizedTestSuiteRegistry()
testing::internal::ParameterizedTestSuiteRegistry::ParameterizedTestSuiteRegistry () inline
Definition at line 686 of file gtest-param-util.h.
 {}
~ParameterizedTestSuiteRegistry()
testing::internal::ParameterizedTestSuiteRegistry::~ParameterizedTestSuiteRegistry () inline
Definition at line 687 of file gtest-param-util.h.
{
     for (auto& test_suite_info : test_suite_infos_) {
       delete test_suite_info;
     }
   }
References test_suite_infos_.
Member Function Documentation
GetTestCasePatternHolder()
template<class TestCase > ParameterizedTestCaseInfo<TestCase>* testing::internal::ParameterizedTestSuiteRegistry::GetTestCasePatternHolder (const char * test_case_name, CodeLocation code_location) inline
Definition at line 732 of file gtest-param-util.h.
{
     return GetTestSuitePatternHolder<TestCase>(test_case_name, code_location);
   }
GetTestSuitePatternHolder()
template<class TestSuite > ParameterizedTestSuiteInfo<TestSuite>* testing::internal::ParameterizedTestSuiteRegistry::GetTestSuitePatternHolder (const char * test_suite_name, CodeLocation code_location) inline
Definition at line 696 of file gtest-param-util.h.
{
     ParameterizedTestSuiteInfo<TestSuite>* typed_test_info = nullptr;
     for (auto& test_suite_info : test_suite_infos_) {
       if (test_suite_info->GetTestSuiteName() == test_suite_name) {
         if (test_suite_info->GetTestSuiteTypeId() != GetTypeId<TestSuite>()) {
           // Complain about incorrect usage of Google Test facilities
           // and terminate the program since we cannot guaranty correct
           // test suite setup and tear-down in this case.
           ReportInvalidTestSuiteType(test_suite_name, code_location);
           posix::Abort();
         } else {
           // At this point we are sure that the object we found is of the same
           // type we are looking for, so we downcast it to that type
           // without further checks.
           typed_test_info = CheckedDowncastToActualType<
               ParameterizedTestSuiteInfo<TestSuite> >(test_suite_info);
         }
         break;
       }
     }
     if (typed_test_info == nullptr) {
       typed_test_info = new ParameterizedTestSuiteInfo<TestSuite>(
           test_suite_name, code_location);
       test_suite_infos_.push_back(typed_test_info);
     }
     return typed_test_info;
   }
References testing::internal::posix::Abort(), testing::internal::CheckedDowncastToActualType(), testing::internal::ReportInvalidTestSuiteType(), and test_suite_infos_.
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::internal::ParameterizedTestSuiteRegistry::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ParameterizedTestSuiteRegistry) private
RegisterTests()
void testing::internal::ParameterizedTestSuiteRegistry::RegisterTests () inline
Definition at line 724 of file gtest-param-util.h.
{
     for (auto& test_suite_info : test_suite_infos_) {
       test_suite_info->RegisterTests();
     }
   }
References test_suite_infos_.
Member Data Documentation
test_suite_infos_
TestSuiteInfoContainer testing::internal::ParameterizedTestSuiteRegistry::test_suite_infos_ private
Definition at line 742 of file gtest-param-util.h.
Referenced by GetTestSuitePatternHolder(), RegisterTests(), and ~ParameterizedTestSuiteRegistry().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/internal/gtest-param-util.h