otus_cpp_print_ip: testing::internal::UniversalPrinter< T > Class Template Reference
testing::internal::UniversalPrinter< T > Class Template Reference
#include <gtest-printers.h>
Static Public Member Functions
static void Print (const T &value, ::std::ostream *os)
Detailed Description
template<typename T>
class testing::internal::UniversalPrinter< T >
Definition at line 426 of file gtest-printers.h.
Member Function Documentation
Print()
template<typename T > static void testing::internal::UniversalPrinter< T >::Print (const T & value, ::std::ostream * os) inline static
Definition at line 665 of file gtest-printers.h.
{
     // By default, ::testing::internal::PrintTo() is used for printing
     // the value.
     //
     // Thanks to Koenig look-up, if T is a class and has its own
     // PrintTo() function defined in its namespace, that function will
     // be visible here.  Since it is more specific than the generic ones
     // in ::testing::internal, it will be picked by the compiler in the
     // following statement - exactly what we want.
     PrintTo(value, os);
   }
References testing::internal::PrintTo().
Referenced by GTEST_DISABLE_MSC_WARNINGS_PUSH_(), testing::internal::UniversalTersePrinter< T[N]>::Print(), testing::internal::PrintSmartPointer(), testing::internal::PrintTo(), and testing::internal::UniversalPrint().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/gtest-printers.h