otus_cpp_print_ip: testing::internal::posix Namespace Reference
testing::internal::posix Namespace Reference
Typedefs
typedef struct stat StatStruct
Functions
int FileNo (FILE *file)
int DoIsATTY (int fd)
int Stat (const char *path, StatStruct *buf)
int StrCaseCmp (const char *s1, const char *s2)
char * StrDup (const char *src)
int RmDir (const char *dir)
bool IsDir (const StatStruct &st)
int IsATTY (int fd)
int ChDir (const char *dir)
FILE * FOpen (const char *path, const char *mode)
FILE * FReopen (const char *path, const char *mode, FILE *stream)
FILE * FDOpen (int fd, const char *mode)
int FClose (FILE *fp)
int Read (int fd, void *buf, unsigned int count)
int Write (int fd, const void *buf, unsigned int count)
int Close (int fd)
const char * StrError (int errnum)
const char * GetEnv (const char *name)
void Abort ()
Typedef Documentation
StatStruct
typedef struct stat testing::internal::posix::StatStruct
Definition at line 2021 of file gtest-port.h.
Function Documentation
Abort()
void testing::internal::posix::Abort () inline
Definition at line 2109 of file gtest-port.h.
 { abort(); }
Referenced by testing::internal::ParameterizedTestSuiteRegistry::GetTestSuitePatternHolder(), testing::internal::GTEST_DISABLE_MSC_WARNINGS_PUSH_(), and testing::internal::TypeParameterizedTestSuite< Fixture, Tests, Types >::Register().
ChDir()
int testing::internal::posix::ChDir (const char * dir) inline
Definition at line 2055 of file gtest-port.h.
 { return chdir(dir); }
Close()
int testing::internal::posix::Close (int fd) inline
Definition at line 2082 of file gtest-port.h.
 { return close(fd); }
DoIsATTY()
int testing::internal::posix::DoIsATTY (int fd) inline
Definition at line 2024 of file gtest-port.h.
 { return isatty(fd); }
Referenced by IsATTY().
FClose()
int testing::internal::posix::FClose (FILE * fp) inline
Definition at line 2074 of file gtest-port.h.
 { return fclose(fp); }
FDOpen()
FILE* testing::internal::posix::FDOpen (int fd, const char * mode) inline
Definition at line 2072 of file gtest-port.h.
 { return fdopen(fd, mode); }
FileNo()
int testing::internal::posix::FileNo (FILE * file) inline
Definition at line 2023 of file gtest-port.h.
 { return fileno(file); }
FOpen()
FILE* testing::internal::posix::FOpen (const char * path, const char * mode) inline
Definition at line 2057 of file gtest-port.h.
{
 #if GTEST_OS_WINDOWS && !GTEST_OS_WINDOWS_MINGW
   struct wchar_codecvt : public std::codecvt<wchar_t, char, std::mbstate_t> {};
   std::wstring_convert<wchar_codecvt> converter;
   std::wstring wide_path = converter.from_bytes(path);
   std::wstring wide_mode = converter.from_bytes(mode);
   return _wfopen(wide_path.c_str(), wide_mode.c_str());
 #else  // GTEST_OS_WINDOWS && !GTEST_OS_WINDOWS_MINGW
   return fopen(path, mode);
 #endif  // GTEST_OS_WINDOWS && !GTEST_OS_WINDOWS_MINGW
 }
FReopen()
FILE* testing::internal::posix::FReopen (const char * path, const char * mode, FILE * stream) inline
Definition at line 2069 of file gtest-port.h.
{
   return freopen(path, mode, stream);
 }
GetEnv()
const char* testing::internal::posix::GetEnv (const char * name) inline
Definition at line 2085 of file gtest-port.h.
{
 #if GTEST_OS_WINDOWS_MOBILE || GTEST_OS_WINDOWS_PHONE || \
     GTEST_OS_WINDOWS_RT || GTEST_OS_ESP8266
   // We are on an embedded platform, which has no environment variables.
   static_cast<void>(name);  // To prevent 'unused argument' warning.
   return nullptr;
 #elif defined(__BORLANDC__) || defined(__SunOS_5_8) || defined(__SunOS_5_9)
   // Environment variables which we programmatically clear will be set to the
   // empty string rather than unset (NULL).  Handle that case.
   const char* const env = getenv(name);
   return (env != nullptr && env[0] != '\0') ? env : nullptr;
 #else
   return getenv(name);
 #endif
 }
IsATTY()
int testing::internal::posix::IsATTY (int fd) inline
Definition at line 2035 of file gtest-port.h.
{
   // DoIsATTY might change errno (for example ENOTTY in case you redirect stdout
   // to a file on Linux), which is unexpected, so save the previous value, and
   // restore it after the call.
   int savedErrno = errno;
   int isAttyValue = DoIsATTY(fd);
   errno = savedErrno;
   return isAttyValue;
 }
References DoIsATTY().
IsDir()
bool testing::internal::posix::IsDir (const StatStruct & st) inline
Definition at line 2031 of file gtest-port.h.
 { return S_ISDIR(st.st_mode); }
Read()
int testing::internal::posix::Read (int fd, void * buf, unsigned int count) inline
Definition at line 2076 of file gtest-port.h.
{
   return static_cast<int>(read(fd, buf, count));
 }
RmDir()
int testing::internal::posix::RmDir (const char * dir) inline
Definition at line 2030 of file gtest-port.h.
 { return rmdir(dir); }
Stat()
int testing::internal::posix::Stat (const char * path, StatStruct * buf) inline
Definition at line 2025 of file gtest-port.h.
 { return stat(path, buf); }
StrCaseCmp()
int testing::internal::posix::StrCaseCmp (const char * s1, const char * s2) inline
Definition at line 2026 of file gtest-port.h.
{
   return strcasecmp(s1, s2);
 }
StrDup()
char* testing::internal::posix::StrDup (const char * src) inline
Definition at line 2029 of file gtest-port.h.
 { return strdup(src); }
StrError()
const char* testing::internal::posix::StrError (int errnum) inline
Definition at line 2083 of file gtest-port.h.
 { return strerror(errnum); }
Write()
int testing::internal::posix::Write (int fd, const void * buf, unsigned int count) inline
Definition at line 2079 of file gtest-port.h.
{
   return static_cast<int>(write(fd, buf, count));
 }