otus_cpp_print_ip: testing::internal::TypeParameterizedTest< Fixture, TestSel, Types > Class Template Reference
testing::internal::TypeParameterizedTest< Fixture, TestSel, Types > Class Template Reference
#include <gtest-internal.h>
Static Public Member Functions
static bool Register (const char *prefix, const CodeLocation &code_location, const char *case_name, const char *test_names, int index, const std::vector< std::string > &type_names=GenerateNames< DefaultNameGenerator, Types >())
Detailed Description
template<GTEST_TEMPLATE_ Fixture, class TestSel, typename Types>
class testing::internal::TypeParameterizedTest< Fixture, TestSel, Types >
Definition at line 712 of file gtest-internal.h.
Member Function Documentation
Register()
template<GTEST_TEMPLATE_ Fixture, class TestSel , typename Types > static bool testing::internal::TypeParameterizedTest< Fixture, TestSel, Types >::Register (const char * prefix, const CodeLocation & code_location, const char * case_name, const char * test_names, int index, const std::vector< std::string > & type_names = GenerateNames<DefaultNameGenerator, Types>()) inline static
Definition at line 718 of file gtest-internal.h.
{
     typedef typename Types::Head Type;
     typedef Fixture<Type> FixtureClass;
     typedef typename GTEST_BIND_(TestSel, Type) TestClass;
     // First, registers the first type-parameterized test in the type
     // list.
     MakeAndRegisterTestInfo(
         (std::string(prefix) + (prefix[0] == '\0' ? "" : "/") + case_name +
          "/" + type_names[static_cast<size_t>(index)])
             .c_str(),
         StripTrailingSpaces(GetPrefixUntilComma(test_names)).c_str(),
         GetTypeName<Type>().c_str(),
         nullptr,  // No value parameter.
         code_location, GetTypeId<FixtureClass>(),
         SuiteApiResolver<TestClass>::GetSetUpCaseOrSuite(
             code_location.file.c_str(), code_location.line),
         SuiteApiResolver<TestClass>::GetTearDownCaseOrSuite(
             code_location.file.c_str(), code_location.line),
         new TestFactoryImpl<TestClass>);
     // Next, recurses (at compile time) with the tail of the type list.
     return TypeParameterizedTest<Fixture, TestSel,
                                  typename Types::Tail>::Register(prefix,
                                                                  code_location,
                                                                  case_name,
                                                                  test_names,
                                                                  index + 1,
                                                                  type_names);
   }
References testing::internal::CodeLocation::file, testing::internal::GetPrefixUntilComma(), GTEST_BIND_, testing::internal::CodeLocation::line, testing::internal::MakeAndRegisterTestInfo(), and testing::internal::StripTrailingSpaces().
Referenced by testing::internal::TypeParameterizedTestSuite< Fixture, Tests, Types >::Register().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/internal/gtest-internal.h