otus_cpp_print_ip: testing::internal::TypeParameterizedTestSuite< Fixture, Tests, Types > Class Template Reference
testing::internal::TypeParameterizedTestSuite< Fixture, Tests, Types > Class Template Reference
#include <gtest-internal.h>
Static Public Member Functions
static bool Register (const char *prefix, CodeLocation code_location, const TypedTestSuitePState *state, const char *case_name, const char *test_names, const std::vector< std::string > &type_names=GenerateNames< DefaultNameGenerator, Types >())
Detailed Description
template<GTEST_TEMPLATE_ Fixture, typename Tests, typename Types>
class testing::internal::TypeParameterizedTestSuite< Fixture, Tests, Types >
Definition at line 776 of file gtest-internal.h.
Member Function Documentation
Register()
template<GTEST_TEMPLATE_ Fixture, typename Tests , typename Types > static bool testing::internal::TypeParameterizedTestSuite< Fixture, Tests, Types >::Register (const char * prefix, CodeLocation code_location, const TypedTestSuitePState * state, const char * case_name, const char * test_names, const std::vector< std::string > & type_names = GenerateNames<DefaultNameGenerator, Types>()) inline static
Definition at line 778 of file gtest-internal.h.
{
     RegisterTypeParameterizedTestSuiteInstantiation(case_name);
     std::string test_name = StripTrailingSpaces(
         GetPrefixUntilComma(test_names));
     if (!state->TestExists(test_name)) {
       fprintf(stderr, "Failed to get code location for test %s.%s at %s.",
               case_name, test_name.c_str(),
               FormatFileLocation(code_location.file.c_str(),
                                  code_location.line).c_str());
       fflush(stderr);
       posix::Abort();
     }
     const CodeLocation& test_location = state->GetCodeLocation(test_name);
     typedef typename Tests::Head Head;
     // First, register the first test in 'Test' for each type in 'Types'.
     TypeParameterizedTest<Fixture, Head, Types>::Register(
         prefix, test_location, case_name, test_names, 0, type_names);
     // Next, recurses (at compile time) with the tail of the test list.
     return TypeParameterizedTestSuite<Fixture, typename Tests::Tail,
                                       Types>::Register(prefix, code_location,
                                                        state, case_name,
                                                        SkipComma(test_names),
                                                        type_names);
   }
References testing::internal::posix::Abort(), testing::internal::CodeLocation::file, testing::internal::FormatFileLocation(), testing::internal::GetPrefixUntilComma(), testing::internal::CodeLocation::line, testing::internal::TypeParameterizedTest< Fixture, TestSel, Types >::Register(), testing::internal::RegisterTypeParameterizedTestSuiteInstantiation(), and testing::internal::StripTrailingSpaces().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/internal/gtest-internal.h