otus_cpp_print_ip: testing Namespace Reference
testing Namespace Reference
Namespaces
internal
Classes
class Action
class ActionInterface
class DefaultValue
class DefaultValue< T & >
class DefaultValue< void >
class EmptyTestEventListener
class Environment
class Matcher
class Message
class NaggyMock
class NiceMock
class PolymorphicAction
struct PrintToStringParamName
class ScopedTrace
class StrictMock
class Test
class TestEventListener
class TestEventListeners
class TestInfo
struct TestParamInfo
class TestProperty
class TestResult
class TestSuite
class TestWithParam
class UnitTest
class WithParamInterface
Typedefs
typedef internal::IgnoredValue Unused
typedef internal::TimeInMillis TimeInMillis
template<typename... Ts>
using Types = internal::ProxyTypeList< Ts... >
Functions
template<typename F >
Action< F > MakeAction (ActionInterface< F > *impl)
template<typename Impl >
PolymorphicAction< Impl > MakePolymorphicAction (const Impl &impl)
template<typename... Action>
internal::DoAllAction< typename std::decay< Action >::type... > DoAll (Action &&... action)
template<size_t k, typename InnerAction >
internal::WithArgsAction< typename std::decay< InnerAction >::type, k > WithArg (InnerAction &&action)
template<size_t k, size_t... ks, typename InnerAction >
internal::WithArgsAction< typename std::decay< InnerAction >::type, k, ks... > WithArgs (InnerAction &&action)
template<typename InnerAction >
internal::WithArgsAction< typename std::decay< InnerAction >::type > WithoutArgs (InnerAction &&action)
template<typename R >
internal::ReturnAction< R > Return (R value)
PolymorphicAction< internal::ReturnNullAction > ReturnNull ()
PolymorphicAction< internal::ReturnVoidAction > Return ()
template<typename R >
internal::ReturnRefAction< R > ReturnRef (R &x)
template<typename R , R * = nullptr>
internal::ReturnRefAction< R > ReturnRef (R &&)=delete
template<typename R >
internal::ReturnRefOfCopyAction< R > ReturnRefOfCopy (const R &x)
template<typename R >
internal::ByMoveWrapper< R > ByMove (R x)
template<typename T >
internal::ReturnRoundRobinAction< T > ReturnRoundRobin (std::vector< T > vals)
template<typename T >
internal::ReturnRoundRobinAction< T > ReturnRoundRobin (std::initializer_list< T > vals)
internal::DoDefaultAction DoDefault ()
template<size_t N, typename T >
internal::SetArgumentPointeeAction< N, T > SetArgPointee (T value)
template<size_t N, typename T >
internal::SetArgumentPointeeAction< N, T > SetArgumentPointee (T value)
template<typename T1 , typename T2 >
PolymorphicAction< internal::AssignAction< T1, T2 > > Assign (T1 *ptr, T2 val)
template<typename T >
PolymorphicAction< internal::SetErrnoAndReturnAction< T > > SetErrnoAndReturn (int errval, T result)
template<typename FunctionImpl >
std::decay< FunctionImpl >::type Invoke (FunctionImpl &&function_impl)
template<class Class , typename MethodPtr >
internal::InvokeMethodAction< Class, MethodPtr > Invoke (Class *obj_ptr, MethodPtr method_ptr)
template<typename FunctionImpl >
internal::InvokeWithoutArgsAction< typename std::decay< FunctionImpl >::type > InvokeWithoutArgs (FunctionImpl function_impl)
template<class Class , typename MethodPtr >
internal::InvokeMethodWithoutArgsAction< Class, MethodPtr > InvokeWithoutArgs (Class *obj_ptr, MethodPtr method_ptr)
template<typename A >
internal::IgnoreResultAction< A > IgnoreResult (const A &an_action)
template<typename T >
inline ::std::reference_wrapper< T > ByRef (T &l_value)
template<typename T , typename... Params>
internal::ReturnNewAction< T, typename std::decay< Params >::type... > ReturnNew (Params &&... params)
template<size_t k>
internal::ReturnArgAction< k > ReturnArg ()
template<size_t k, typename Ptr >
internal::SaveArgAction< k, Ptr > SaveArg (Ptr pointer)
template<size_t k, typename Ptr >
internal::SaveArgPointeeAction< k, Ptr > SaveArgPointee (Ptr pointer)
template<size_t k, typename T >
internal::SetArgRefereeAction< k, typename std::decay< T >::type > SetArgReferee (T &&value)
template<size_t k, typename I1 , typename I2 >
internal::SetArrayArgumentAction< k, I1, I2 > SetArrayArgument (I1 first, I2 last)
template<size_t k>
internal::DeleteArgAction< k > DeleteArg ()
template<typename Ptr >
internal::ReturnPointeeAction< Ptr > ReturnPointee (Ptr pointer)
template<std::size_t index, typename... Params>
internal::InvokeArgumentAction< index, typename std::decay< Params >::type... > InvokeArgument (Params &&... params)
MATCHER (IsEmpty, negation ? "isn't empty" :"is empty")
MATCHER (IsTrue, negation ? "is false" :"is true")
MATCHER (IsFalse, negation ? "is true" :"is false")
GMOCK_DECLARE_bool_ (catch_leaked_mocks)
GMOCK_DECLARE_string_ (verbose)
GMOCK_DECLARE_int32_ (default_mock_behavior)
GTEST_API_ void InitGoogleMock (int *argc, char **argv)
GTEST_API_ void InitGoogleMock (int *argc, wchar_t **argv)
GTEST_API_ void InitGoogleMock ()
GTEST_DECLARE_string_ (death_test_style)
std::ostream & operator<< (std::ostream &os, const Message &sb)
template<typename T , typename IncrementT >
internal::ParamGenerator< T > Range (T start, T end, IncrementT step)
template<typename T >
internal::ParamGenerator< T > Range (T start, T end)
template<typename ForwardIterator >
internal::ParamGenerator< typename std::iterator_traits< ForwardIterator >::value_type > ValuesIn (ForwardIterator begin, ForwardIterator end)
template<typename T , size_t N>
internal::ParamGenerator< T > ValuesIn (const T(&array)[N])
template<class Container >
internal::ParamGenerator< typename Container::value_type > ValuesIn (const Container &container)
template<typename... T>
internal::ValueArray< T... > Values (T... v)
internal::ParamGenerator< bool > Bool ()
template<typename... Generator>
internal::CartesianProductHolder< Generator... > Combine (const Generator &... g)
template<typename T >
::std::string PrintToString (const T &value)
Environment * AddGlobalTestEnvironment (Environment *env)
GTEST_API_ void InitGoogleTest (int *argc, char **argv)
GTEST_API_ void InitGoogleTest (int *argc, wchar_t **argv)
GTEST_API_ void InitGoogleTest ()
GTEST_API_ AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
GTEST_API_ AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
GTEST_API_ AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const char *needle, const char *haystack)
GTEST_API_ AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const wchar_t *needle, const wchar_t *haystack)
GTEST_API_ AssertionResult IsSubstring (const char *needle_expr, const char *haystack_expr, const ::std::string &needle, const ::std::string &haystack)
GTEST_API_ AssertionResult IsNotSubstring (const char *needle_expr, const char *haystack_expr, const ::std::string &needle, const ::std::string &haystack)
GTEST_API_ AssertionResult FloatLE (const char *expr1, const char *expr2, float val1, float val2)
GTEST_API_ AssertionResult DoubleLE (const char *expr1, const char *expr2, double val1, double val2)
template<typename T1 , typename T2 >
constexpr bool StaticAssertTypeEq () noexcept
GTEST_API_ std::string TempDir ()
template<int &... ExplicitParameterBarrier, typename Factory >
TestInfo * RegisterTest (const char *test_suite_name, const char *test_name, const char *type_param, const char *value_param, const char *file, int line, Factory factory)
template<typename Pred , typename T1 >
AssertionResult AssertPred1Helper (const char *pred_text, const char *e1, Pred pred, const T1 &v1)
template<typename Pred , typename T1 , typename T2 >
AssertionResult AssertPred2Helper (const char *pred_text, const char *e1, const char *e2, Pred pred, const T1 &v1, const T2 &v2)
template<typename Pred , typename T1 , typename T2 , typename T3 >
AssertionResult AssertPred3Helper (const char *pred_text, const char *e1, const char *e2, const char *e3, Pred pred, const T1 &v1, const T2 &v2, const T3 &v3)
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 >
AssertionResult AssertPred4Helper (const char *pred_text, const char *e1, const char *e2, const char *e3, const char *e4, Pred pred, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4)
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
AssertionResult AssertPred5Helper (const char *pred_text, const char *e1, const char *e2, const char *e3, const char *e4, const char *e5, Pred pred, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5)
Variables
class GTEST_API_ testing::ScopedTrace GTEST_ATTRIBUTE_UNUSED_
Typedef Documentation
TimeInMillis
typedef internal::TimeInMillis testing::TimeInMillis
Definition at line 528 of file gtest.h.
Types
template<typename... Ts> using testing::Types = typedef internal::ProxyTypeList<Ts...>
Definition at line 179 of file gtest-type-util.h.
Unused
typedef internal::IgnoredValue testing::Unused
Definition at line 1198 of file gmock-actions.h.
Function Documentation
AddGlobalTestEnvironment()
Environment* testing::AddGlobalTestEnvironment (Environment * env) inline
Definition at line 1493 of file gtest.h.
{
   return UnitTest::GetInstance()->AddEnvironment(env);
 }
References testing::UnitTest::AddEnvironment(), and testing::UnitTest::GetInstance().
AssertPred1Helper()
template<typename Pred , typename T1 > AssertionResult testing::AssertPred1Helper (const char * pred_text, const char * e1, Pred pred, const T1 & v1)
Definition at line 87 of file gtest_pred_impl.h.
{
   if (pred(v1)) return AssertionSuccess();
   return AssertionFailure()
          << pred_text << "(" << e1 << ") evaluates to false, where"
          << "\n"
          << e1 << " evaluates to " << ::testing::PrintToString(v1);
 }
References PrintToString().
AssertPred2Helper()
template<typename Pred , typename T1 , typename T2 > AssertionResult testing::AssertPred2Helper (const char * pred_text, const char * e1, const char * e2, Pred pred, const T1 & v1, const T2 & v2)
Definition at line 130 of file gtest_pred_impl.h.
{
   if (pred(v1, v2)) return AssertionSuccess();
   return AssertionFailure()
          << pred_text << "(" << e1 << ", " << e2
          << ") evaluates to false, where"
          << "\n"
          << e1 << " evaluates to " << ::testing::PrintToString(v1) << "\n"
          << e2 << " evaluates to " << ::testing::PrintToString(v2);
 }
References PrintToString().
AssertPred3Helper()
template<typename Pred , typename T1 , typename T2 , typename T3 > AssertionResult testing::AssertPred3Helper (const char * pred_text, const char * e1, const char * e2, const char * e3, Pred pred, const T1 & v1, const T2 & v2, const T3 & v3)
Definition at line 180 of file gtest_pred_impl.h.
{
   if (pred(v1, v2, v3)) return AssertionSuccess();
   return AssertionFailure()
          << pred_text << "(" << e1 << ", " << e2 << ", " << e3
          << ") evaluates to false, where"
          << "\n"
          << e1 << " evaluates to " << ::testing::PrintToString(v1) << "\n"
          << e2 << " evaluates to " << ::testing::PrintToString(v2) << "\n"
          << e3 << " evaluates to " << ::testing::PrintToString(v3);
 }
References PrintToString().
AssertPred4Helper()
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 > AssertionResult testing::AssertPred4Helper (const char * pred_text, const char * e1, const char * e2, const char * e3, const char * e4, Pred pred, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4)
Definition at line 236 of file gtest_pred_impl.h.
{
   if (pred(v1, v2, v3, v4)) return AssertionSuccess();
   return AssertionFailure()
          << pred_text << "(" << e1 << ", " << e2 << ", " << e3 << ", " << e4
          << ") evaluates to false, where"
          << "\n"
          << e1 << " evaluates to " << ::testing::PrintToString(v1) << "\n"
          << e2 << " evaluates to " << ::testing::PrintToString(v2) << "\n"
          << e3 << " evaluates to " << ::testing::PrintToString(v3) << "\n"
          << e4 << " evaluates to " << ::testing::PrintToString(v4);
 }
References PrintToString().
AssertPred5Helper()
template<typename Pred , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > AssertionResult testing::AssertPred5Helper (const char * pred_text, const char * e1, const char * e2, const char * e3, const char * e4, const char * e5, Pred pred, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5)
Definition at line 298 of file gtest_pred_impl.h.
{
   if (pred(v1, v2, v3, v4, v5)) return AssertionSuccess();
   return AssertionFailure()
          << pred_text << "(" << e1 << ", " << e2 << ", " << e3 << ", " << e4
          << ", " << e5 << ") evaluates to false, where"
          << "\n"
          << e1 << " evaluates to " << ::testing::PrintToString(v1) << "\n"
          << e2 << " evaluates to " << ::testing::PrintToString(v2) << "\n"
          << e3 << " evaluates to " << ::testing::PrintToString(v3) << "\n"
          << e4 << " evaluates to " << ::testing::PrintToString(v4) << "\n"
          << e5 << " evaluates to " << ::testing::PrintToString(v5);
 }
References PrintToString().
Assign()
template<typename T1 , typename T2 > PolymorphicAction<internal::AssignAction<T1, T2> > testing::Assign (T1 * ptr, T2 val)
Definition at line 1322 of file gmock-actions.h.
{
   return MakePolymorphicAction(internal::AssignAction<T1, T2>(ptr, val));
 }
References MakePolymorphicAction().
Referenced by TEST().
Bool()
internal::ParamGenerator<bool> testing::Bool () inline
Definition at line 357 of file gtest-param-test.h.
{
   return Values(false, true);
 }
References Values().
ByMove()
template<typename R > internal::ByMoveWrapper<R> testing::ByMove (R x)
Definition at line 1281 of file gmock-actions.h.
{
   return internal::ByMoveWrapper<R>(std::move(x));
 }
ByRef()
template<typename T > inline ::std::reference_wrapper<T> testing::ByRef (T & l_value)
Definition at line 1391 of file gmock-actions.h.
                                                  {  // NOLINT
   return ::std::reference_wrapper<T>(l_value);
 }
Combine()
template<typename... Generator> internal::CartesianProductHolder<Generator...> testing::Combine (const Generator &... g)
Definition at line 406 of file gtest-param-test.h.
{
   return internal::CartesianProductHolder<Generator...>(g...);
 }
DeleteArg()
template<size_t k> internal::DeleteArgAction<k> testing::DeleteArg ()
Definition at line 1446 of file gmock-actions.h.
{
   return {};
 }
DoAll()
template<typename... Action> internal::DoAllAction<typename std::decay<Action>::type...> testing::DoAll (Action &&... action)
Definition at line 1204 of file gmock-actions.h.
{
   return {std::forward_as_tuple(std::forward<Action>(action)...)};
 }
Referenced by TEST().
DoDefault()
internal::DoDefaultAction testing::DoDefault () inline
Definition at line 1303 of file gmock-actions.h.
{
   return internal::DoDefaultAction();
 }
Referenced by GTEST_DISABLE_MSC_WARNINGS_PUSH_(), and TEST().
DoubleLE()
GTEST_API_ AssertionResult testing::DoubleLE (const char * expr1, const char * expr2, double val1, double val2)
FloatLE()
GTEST_API_ AssertionResult testing::FloatLE (const char * expr1, const char * expr2, float val1, float val2)
GMOCK_DECLARE_bool_()
testing::GMOCK_DECLARE_bool_ (catch_leaked_mocks)
GMOCK_DECLARE_int32_()
testing::GMOCK_DECLARE_int32_ (default_mock_behavior)
GMOCK_DECLARE_string_()
testing::GMOCK_DECLARE_string_ (verbose)
GTEST_DECLARE_string_()
testing::GTEST_DECLARE_string_ (death_test_style)
IgnoreResult()
template<typename A > internal::IgnoreResultAction<A> testing::IgnoreResult (const A & an_action) inline
Definition at line 1376 of file gmock-actions.h.
{
   return internal::IgnoreResultAction<A>(an_action);
 }
Referenced by TEST().
InitGoogleMock() [1/3]
GTEST_API_ void testing::InitGoogleMock ()
InitGoogleMock() [2/3]
GTEST_API_ void testing::InitGoogleMock (int * argc, char ** argv)
InitGoogleMock() [3/3]
GTEST_API_ void testing::InitGoogleMock (int * argc, wchar_t ** argv)
InitGoogleTest() [1/3]
GTEST_API_ void testing::InitGoogleTest ()
InitGoogleTest() [2/3]
GTEST_API_ void testing::InitGoogleTest (int * argc, char ** argv)
InitGoogleTest() [3/3]
GTEST_API_ void testing::InitGoogleTest (int * argc, wchar_t ** argv)
Invoke() [1/2]
template<class Class , typename MethodPtr > internal::InvokeMethodAction<Class, MethodPtr> testing::Invoke (Class * obj_ptr, MethodPtr method_ptr)
Definition at line 1352 of file gmock-actions.h.
{
   return {obj_ptr, method_ptr};
 }
Invoke() [2/2]
template<typename FunctionImpl > std::decay<FunctionImpl>::type testing::Invoke (FunctionImpl && function_impl)
Definition at line 1345 of file gmock-actions.h.
{
   return std::forward<FunctionImpl>(function_impl);
 }
Referenced by GTEST_DISABLE_MSC_WARNINGS_PUSH_(), and TEST().
InvokeArgument()
template<std::size_t index, typename... Params> internal::InvokeArgumentAction<index, typename std::decay<Params>::type...> testing::InvokeArgument (Params &&... params)
Definition at line 562 of file gmock-more-actions.h.
{
   return {internal::FlatTuple<typename std::decay<Params>::type...>(
       internal::FlatTupleConstructTag{}, std::forward<Params>(params)...)};
 }
InvokeWithoutArgs() [1/2]
template<class Class , typename MethodPtr > internal::InvokeMethodWithoutArgsAction<Class, MethodPtr> testing::InvokeWithoutArgs (Class * obj_ptr, MethodPtr method_ptr)
Definition at line 1367 of file gmock-actions.h.
{
   return {obj_ptr, method_ptr};
 }
InvokeWithoutArgs() [2/2]
template<typename FunctionImpl > internal::InvokeWithoutArgsAction<typename std::decay<FunctionImpl>::type> testing::InvokeWithoutArgs (FunctionImpl function_impl)
Definition at line 1360 of file gmock-actions.h.
{
   return {std::move(function_impl)};
 }
Referenced by TEST().
IsNotSubstring() [1/3]
GTEST_API_ AssertionResult testing::IsNotSubstring (const char * needle_expr, const char * haystack_expr, const ::std::string & needle, const ::std::string & haystack)
IsNotSubstring() [2/3]
GTEST_API_ AssertionResult testing::IsNotSubstring (const char * needle_expr, const char * haystack_expr, const char * needle, const char * haystack)
IsNotSubstring() [3/3]
GTEST_API_ AssertionResult testing::IsNotSubstring (const char * needle_expr, const char * haystack_expr, const wchar_t * needle, const wchar_t * haystack)
IsSubstring() [1/3]
GTEST_API_ AssertionResult testing::IsSubstring (const char * needle_expr, const char * haystack_expr, const ::std::string & needle, const ::std::string & haystack)
IsSubstring() [2/3]
GTEST_API_ AssertionResult testing::IsSubstring (const char * needle_expr, const char * haystack_expr, const char * needle, const char * haystack)
IsSubstring() [3/3]
GTEST_API_ AssertionResult testing::IsSubstring (const char * needle_expr, const char * haystack_expr, const wchar_t * needle, const wchar_t * haystack)
MakeAction()
template<typename F > Action<F> testing::MakeAction (ActionInterface< F > * impl)
Definition at line 583 of file gmock-actions.h.
{
   return Action<F>(impl);
 }
MakePolymorphicAction()
template<typename Impl > PolymorphicAction<Impl> testing::MakePolymorphicAction (const Impl & impl) inline
Definition at line 595 of file gmock-actions.h.
{
   return PolymorphicAction<Impl>(impl);
 }
Referenced by Assign(), Return(), ReturnNull(), and SetErrnoAndReturn().
MATCHER() [1/3]
testing::MATCHER (IsEmpty , negation ? "isn't empty" :"is empty")
Definition at line 61 of file gmock-more-matchers.h.
                                           : "is empty") {
   if (arg.empty()) {
     return true;
   }
   *result_listener << "whose size is " << arg.size();
   return false;
 }
MATCHER() [2/3]
testing::MATCHER (IsFalse , negation ? "is true" :"is false")
Definition at line 81 of file gmock-more-matchers.h.
                                       : "is false") {
   return !static_cast<bool>(arg);
 }
MATCHER() [3/3]
testing::MATCHER (IsTrue , negation ? "is false" :"is true")
Definition at line 73 of file gmock-more-matchers.h.
                                       : "is true") {
   return static_cast<bool>(arg);
 }
operator<<()
std::ostream& testing::operator<< (std::ostream & os, const Message & sb) inline
Definition at line 199 of file gtest-message.h.
{
   return os << sb.GetString();
 }
References testing::Message::GetString().
Referenced by GTEST_DISABLE_MSC_WARNINGS_PUSH_().
PrintToString()
template<typename T > ::std::string testing::PrintToString (const T & value)
Definition at line 942 of file gtest-printers.h.
{
   ::std::stringstream ss;
   internal::UniversalTersePrinter<T>::Print(value, &ss);
   return ss.str();
 }
References testing::internal::UniversalTersePrinter< T >::Print().
Referenced by AssertPred1Helper(), AssertPred2Helper(), AssertPred3Helper(), AssertPred4Helper(), AssertPred5Helper(), testing::internal::FormatForComparison< ToPrint, OtherOperand >::Format(), GTEST_DISABLE_MSC_WARNINGS_PUSH_(), testing::PrintToStringParamName::operator()(), and testing::internal::ParameterizedTestSuiteInfo< TestSuite >::RegisterTests().
Range() [1/2]
template<typename T > internal::ParamGenerator<T> testing::Range (T start, T end)
Definition at line 233 of file gtest-param-test.h.
{
   return Range(start, end, 1);
 }
References Range().
Range() [2/2]
template<typename T , typename IncrementT > internal::ParamGenerator<T> testing::Range (T start, T end, IncrementT step)
Definition at line 227 of file gtest-param-test.h.
{
   return internal::ParamGenerator<T>(
       new internal::RangeGenerator<T, IncrementT>(start, end, step));
 }
Referenced by Range().
RegisterTest()
template<int &... ExplicitParameterBarrier, typename Factory > TestInfo* testing::RegisterTest (const char * test_suite_name, const char * test_name, const char * type_param, const char * value_param, const char * file, int line, Factory factory)
Definition at line 2436 of file gtest.h.
{
   using TestT = typename std::remove_pointer<decltype(factory())>::type;
   class FactoryImpl : public internal::TestFactoryBase {
    public:
     explicit FactoryImpl(Factory f) : factory_(std::move(f)) {}
     Test* CreateTest() override { return factory_(); }
    private:
     Factory factory_;
   };
   return internal::MakeAndRegisterTestInfo(
       test_suite_name, test_name, type_param, value_param,
       internal::CodeLocation(file, line), internal::GetTypeId<TestT>(),
       internal::SuiteApiResolver<TestT>::GetSetUpCaseOrSuite(file, line),
       internal::SuiteApiResolver<TestT>::GetTearDownCaseOrSuite(file, line),
       new FactoryImpl{std::move(factory)});
 }
References testing::internal::MakeAndRegisterTestInfo().
Return() [1/2]
PolymorphicAction<internal::ReturnVoidAction> testing::Return () inline
Definition at line 1254 of file gmock-actions.h.
{
   return MakePolymorphicAction(internal::ReturnVoidAction());
 }
References MakePolymorphicAction().
Return() [2/2]
template<typename R > internal::ReturnAction<R> testing::Return (R value)
Definition at line 1244 of file gmock-actions.h.
{
   return internal::ReturnAction<R>(std::move(value));
 }
Referenced by TEST().
ReturnArg()
template<size_t k> internal::ReturnArgAction<k> testing::ReturnArg ()
Definition at line 1406 of file gmock-actions.h.
{
   return {};
 }
ReturnNew()
template<typename T , typename... Params> internal::ReturnNewAction<T, typename std::decay<Params>::type...> testing::ReturnNew (Params &&... params)
Definition at line 1399 of file gmock-actions.h.
{
   return {std::forward_as_tuple(std::forward<Params>(params)...)};
 }
ReturnNull()
PolymorphicAction<internal::ReturnNullAction> testing::ReturnNull () inline
Definition at line 1249 of file gmock-actions.h.
{
   return MakePolymorphicAction(internal::ReturnNullAction());
 }
References MakePolymorphicAction().
ReturnPointee()
template<typename Ptr > internal::ReturnPointeeAction<Ptr> testing::ReturnPointee (Ptr pointer)
Definition at line 1452 of file gmock-actions.h.
{
   return {pointer};
 }
ReturnRef() [1/2]
template<typename R , R * = nullptr> internal::ReturnRefAction<R> testing::ReturnRef (R &&) delete
ReturnRef() [2/2]
template<typename R > internal::ReturnRefAction<R> testing::ReturnRef (R & x) inline
Definition at line 1260 of file gmock-actions.h.
                                                   {  // NOLINT
   return internal::ReturnRefAction<R>(x);
 }
Referenced by TEST().
ReturnRefOfCopy()
template<typename R > internal::ReturnRefOfCopyAction<R> testing::ReturnRefOfCopy (const R & x) inline
Definition at line 1272 of file gmock-actions.h.
{
   return internal::ReturnRefOfCopyAction<R>(x);
 }
ReturnRoundRobin() [1/2]
template<typename T > internal::ReturnRoundRobinAction<T> testing::ReturnRoundRobin (std::initializer_list< T > vals)
Definition at line 1297 of file gmock-actions.h.
{
   return internal::ReturnRoundRobinAction<T>(std::vector<T>(vals));
 }
ReturnRoundRobin() [2/2]
template<typename T > internal::ReturnRoundRobinAction<T> testing::ReturnRoundRobin (std::vector< T > vals)
Definition at line 1289 of file gmock-actions.h.
{
   return internal::ReturnRoundRobinAction<T>(std::move(vals));
 }
SaveArg()
template<size_t k, typename Ptr > internal::SaveArgAction<k, Ptr> testing::SaveArg (Ptr pointer)
Definition at line 1413 of file gmock-actions.h.
{
   return {pointer};
 }
SaveArgPointee()
template<size_t k, typename Ptr > internal::SaveArgPointeeAction<k, Ptr> testing::SaveArgPointee (Ptr pointer)
Definition at line 1420 of file gmock-actions.h.
{
   return {pointer};
 }
SetArgPointee()
template<size_t N, typename T > internal::SetArgumentPointeeAction<N, T> testing::SetArgPointee (T value)
Definition at line 1310 of file gmock-actions.h.
{
   return {std::move(value)};
 }
SetArgReferee()
template<size_t k, typename T > internal::SetArgRefereeAction<k, typename std::decay<T>::type> testing::SetArgReferee (T && value)
Definition at line 1427 of file gmock-actions.h.
                {
   return {std::forward<T>(value)};
 }
SetArgumentPointee()
template<size_t N, typename T > internal::SetArgumentPointeeAction<N, T> testing::SetArgumentPointee (T value)
Definition at line 1316 of file gmock-actions.h.
{
   return {std::move(value)};
 }
SetArrayArgument()
template<size_t k, typename I1 , typename I2 > internal::SetArrayArgumentAction<k, I1, I2> testing::SetArrayArgument (I1 first, I2 last)
Definition at line 1438 of file gmock-actions.h.
{
   return {first, last};
 }
SetErrnoAndReturn()
template<typename T > PolymorphicAction<internal::SetErrnoAndReturnAction<T> > testing::SetErrnoAndReturn (int errval, T result)
Definition at line 1331 of file gmock-actions.h.
{
   return MakePolymorphicAction(
       internal::SetErrnoAndReturnAction<T>(errval, result));
 }
References MakePolymorphicAction().
Referenced by TEST().
StaticAssertTypeEq()
template<typename T1 , typename T2 > constexpr bool testing::StaticAssertTypeEq () constexpr noexcept
Definition at line 2297 of file gtest.h.
{
   static_assert(std::is_same<T1, T2>::value, "T1 and T2 are not the same type");
   return true;
 }
TempDir()
GTEST_API_ std::string testing::TempDir ()
Values()
template<typename... T> internal::ValueArray<T...> testing::Values (T... v)
Definition at line 333 of file gtest-param-test.h.
{
   return internal::ValueArray<T...>(std::move(v)...);
 }
Referenced by Bool().
ValuesIn() [1/3]
template<class Container > internal::ParamGenerator< typename Container::value_type > testing::ValuesIn (const Container & container)
Definition at line 307 of file gtest-param-test.h.
{
   return ValuesIn(container.begin(), container.end());
 }
References ValuesIn().
ValuesIn() [2/3]
template<typename T , size_t N> internal::ParamGenerator<T> testing::ValuesIn (const T(&) array[N])
Definition at line 302 of file gtest-param-test.h.
{
   return ValuesIn(array, array + N);
 }
References ValuesIn().
ValuesIn() [3/3]
template<typename ForwardIterator > internal::ParamGenerator< typename std::iterator_traits<ForwardIterator>::value_type> testing::ValuesIn (ForwardIterator begin, ForwardIterator end)
Definition at line 295 of file gtest-param-test.h.
{
   typedef typename std::iterator_traits<ForwardIterator>::value_type ParamType;
   return internal::ParamGenerator<ParamType>(
       new internal::ValuesInIteratorRangeGenerator<ParamType>(begin, end));
 }
Referenced by testing::internal::ValueArray< Ts >::operator ParamGenerator< T >(), and ValuesIn().
WithArg()
template<size_t k, typename InnerAction > internal::WithArgsAction<typename std::decay<InnerAction>::type, k> testing::WithArg (InnerAction && action)
Definition at line 1216 of file gmock-actions.h.
{
   return {std::forward<InnerAction>(action)};
 }
WithArgs()
template<size_t k, size_t... ks, typename InnerAction > internal::WithArgsAction<typename std::decay<InnerAction>::type, k, ks...> testing::WithArgs (InnerAction && action)
Definition at line 1226 of file gmock-actions.h.
{
   return {std::forward<InnerAction>(action)};
 }
WithoutArgs()
template<typename InnerAction > internal::WithArgsAction<typename std::decay<InnerAction>::type> testing::WithoutArgs (InnerAction && action)
Definition at line 1236 of file gmock-actions.h.
{
   return {std::forward<InnerAction>(action)};
 }
Referenced by TEST().
Variable Documentation
GTEST_ATTRIBUTE_UNUSED_
class GTEST_API_ testing::ScopedTrace testing::GTEST_ATTRIBUTE_UNUSED_