otus_cpp_print_ip: testing::internal::ParamIteratorInterface< T > Class Template Reference
testing::internal::ParamIteratorInterface< T > Class Template Reference abstract
#include <gtest-param-util.h>
Public Member Functions
virtual ~ParamIteratorInterface ()
virtual const ParamGeneratorInterface< T > * BaseGenerator () const =0
virtual void Advance ()=0
virtual ParamIteratorInterface * Clone () const =0
virtual const T * Current () const =0
virtual bool Equals (const ParamIteratorInterface &other) const =0
Detailed Description
template<typename T>
class testing::internal::ParamIteratorInterface< T >
Definition at line 93 of file gtest-param-util.h.
Constructor & Destructor Documentation
~ParamIteratorInterface()
template<typename T > virtual testing::internal::ParamIteratorInterface< T >::~ParamIteratorInterface () inline virtual
Definition at line 95 of file gtest-param-util.h.
 {}
Member Function Documentation
Advance()
template<typename T > virtual void testing::internal::ParamIteratorInterface< T >::Advance () pure virtual
Implemented in testing::internal::CartesianProductGenerator< T >::IteratorImpl< IndexSequence< I... > >, testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator, and testing::internal::RangeGenerator< T, IncrementT >::Iterator.
BaseGenerator()
template<typename T > virtual const ParamGeneratorInterface<T>* testing::internal::ParamIteratorInterface< T >::BaseGenerator () const pure virtual
Implemented in testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator, and testing::internal::RangeGenerator< T, IncrementT >::Iterator.
Referenced by testing::internal::RangeGenerator< T, IncrementT >::Iterator::Equals(), testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Equals(), and testing::internal::CartesianProductGenerator< T >::IteratorImpl< IndexSequence< I... > >::Equals().
Clone()
template<typename T > virtual ParamIteratorInterface* testing::internal::ParamIteratorInterface< T >::Clone () const pure virtual
Implemented in testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator, and testing::internal::RangeGenerator< T, IncrementT >::Iterator.
Current()
template<typename T > virtual const T* testing::internal::ParamIteratorInterface< T >::Current () const pure virtual
Implemented in testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator, and testing::internal::RangeGenerator< T, IncrementT >::Iterator.
Equals()
template<typename T > virtual bool testing::internal::ParamIteratorInterface< T >::Equals (const ParamIteratorInterface< T > & other) const pure virtual
Implemented in testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator, and testing::internal::RangeGenerator< T, IncrementT >::Iterator.
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/internal/gtest-param-util.h