otus_cpp_print_ip: testing::internal::EqHelper Class Reference
testing::internal::EqHelper Class Reference
#include <gtest.h>
Static Public Member Functions
template<typename T1 , typename T2 , typename std::enable_if<!std::is_integral< T1 >::value||!std::is_pointer< T2 >::value >::type * = nullptr>
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs)
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, BiggestInt lhs, BiggestInt rhs)
template<typename T >
static AssertionResult Compare (const char *lhs_expression, const char *rhs_expression, std::nullptr_t, T *rhs)
Detailed Description
Definition at line 1552 of file gtest.h.
Member Function Documentation
Compare() [1/3]
static AssertionResult testing::internal::EqHelper::Compare (const char * lhs_expression, const char * rhs_expression, BiggestInt lhs, BiggestInt rhs) inline static
Definition at line 1573 of file gtest.h.
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
References testing::internal::CmpHelperEQ().
Compare() [2/3]
template<typename T1 , typename T2 , typename std::enable_if<!std::is_integral< T1 >::value||!std::is_pointer< T2 >::value >::type * = nullptr> static AssertionResult testing::internal::EqHelper::Compare (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs) inline static
Definition at line 1561 of file gtest.h.
{
     return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
   }
References testing::internal::CmpHelperEQ().
Compare() [3/3]
template<typename T > static AssertionResult testing::internal::EqHelper::Compare (const char * lhs_expression, const char * rhs_expression, std::nullptr_t , T * rhs) inline static
Definition at line 1581 of file gtest.h.
{
     // We already know that 'lhs' is a null pointer.
     return CmpHelperEQ(lhs_expression, rhs_expression, static_cast<T*>(nullptr),
                        rhs);
   }
References testing::internal::CmpHelperEQ().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/gtest.h