otus_cpp_print_ip: testing::internal::ParameterizedTestSuiteInfo< TestSuite > Class Template Reference
testing::internal::ParameterizedTestSuiteInfo< TestSuite > Class Template Reference
#include <gtest-param-util.h>
Classes
struct InstantiationInfo
struct TestInfo
Public Types
using ParamType = typename TestSuite::ParamType
using ParamNameGeneratorFunc = std::string(const TestParamInfo< ParamType > &)
Public Member Functions
typedef ParamGenerator (GeneratorCreationFunc)()
ParameterizedTestSuiteInfo (const char *name, CodeLocation code_location)
const std::string & GetTestSuiteName () const override
TypeId GetTestSuiteTypeId () const override
void AddTestPattern (const char *test_suite_name, const char *test_base_name, TestMetaFactoryBase< ParamType > *meta_factory, CodeLocation code_location)
int AddTestSuiteInstantiation (const std::string &instantiation_name, GeneratorCreationFunc *func, ParamNameGeneratorFunc *name_func, const char *file, int line)
void RegisterTests () override
Public Member Functions inherited from testing::internal::ParameterizedTestSuiteInfoBase
virtual ~ParameterizedTestSuiteInfoBase ()
Private Types
using TestInfoContainer = ::std::vector< std::shared_ptr< TestInfo > >
typedef ::std::vector< InstantiationInfo > InstantiationContainer
Private Member Functions
GTEST_DISALLOW_COPY_AND_ASSIGN_ (ParameterizedTestSuiteInfo)
Static Private Member Functions
static bool IsValidParamName (const std::string &name)
Private Attributes
const std::string test_suite_name_
CodeLocation code_location_
TestInfoContainer tests_
InstantiationContainer instantiations_
Additional Inherited Members
Protected Member Functions inherited from testing::internal::ParameterizedTestSuiteInfoBase
ParameterizedTestSuiteInfoBase ()
Detailed Description
template<class TestSuite>
class testing::internal::ParameterizedTestSuiteInfo< TestSuite >
Definition at line 496 of file gtest-param-util.h.
Member Typedef Documentation
InstantiationContainer
template<class TestSuite > typedef ::std::vector<InstantiationInfo> testing::internal::ParameterizedTestSuiteInfo< TestSuite >::InstantiationContainer private
Definition at line 648 of file gtest-param-util.h.
ParamNameGeneratorFunc
template<class TestSuite > using testing::internal::ParameterizedTestSuiteInfo< TestSuite >::ParamNameGeneratorFunc = std::string(const TestParamInfo<ParamType>&)
Definition at line 504 of file gtest-param-util.h.
ParamType
template<class TestSuite > using testing::internal::ParameterizedTestSuiteInfo< TestSuite >::ParamType = typename TestSuite::ParamType
Definition at line 501 of file gtest-param-util.h.
TestInfoContainer
template<class TestSuite > using testing::internal::ParameterizedTestSuiteInfo< TestSuite >::TestInfoContainer = ::std::vector<std::shared_ptr<TestInfo> > private
Definition at line 626 of file gtest-param-util.h.
Constructor & Destructor Documentation
ParameterizedTestSuiteInfo()
template<class TestSuite > testing::internal::ParameterizedTestSuiteInfo< TestSuite >::ParameterizedTestSuiteInfo (const char * name, CodeLocation code_location) inline explicit
Definition at line 506 of file gtest-param-util.h.
       : test_suite_name_(name), code_location_(code_location) {}
Member Function Documentation
AddTestPattern()
template<class TestSuite > void testing::internal::ParameterizedTestSuiteInfo< TestSuite >::AddTestPattern (const char * test_suite_name, const char * test_base_name, TestMetaFactoryBase< ParamType > * meta_factory, CodeLocation code_location) inline
Definition at line 522 of file gtest-param-util.h.
{
     tests_.push_back(std::shared_ptr<TestInfo>(new TestInfo(
         test_suite_name, test_base_name, meta_factory, code_location)));
   }
References testing::internal::ParameterizedTestSuiteInfo< TestSuite >::tests_.
AddTestSuiteInstantiation()
template<class TestSuite > int testing::internal::ParameterizedTestSuiteInfo< TestSuite >::AddTestSuiteInstantiation (const std::string & instantiation_name, GeneratorCreationFunc * func, ParamNameGeneratorFunc * name_func, const char * file, int line) inline
Definition at line 530 of file gtest-param-util.h.
{
     instantiations_.push_back(
         InstantiationInfo(instantiation_name, func, name_func, file, line));
     return 0;  // Return value used only to run this method in namespace scope.
   }
References testing::internal::ParameterizedTestSuiteInfo< TestSuite >::instantiations_.
GetTestSuiteName()
template<class TestSuite > const std::string& testing::internal::ParameterizedTestSuiteInfo< TestSuite >::GetTestSuiteName () const inline override virtual
Implements testing::internal::ParameterizedTestSuiteInfoBase.
Definition at line 511 of file gtest-param-util.h.
{
     return test_suite_name_;
   }
References testing::internal::ParameterizedTestSuiteInfo< TestSuite >::test_suite_name_.
Referenced by testing::internal::ParameterizedTestSuiteInfo< TestSuite >::RegisterTests().
GetTestSuiteTypeId()
template<class TestSuite > TypeId testing::internal::ParameterizedTestSuiteInfo< TestSuite >::GetTestSuiteTypeId () const inline override virtual
Implements testing::internal::ParameterizedTestSuiteInfoBase.
Definition at line 515 of file gtest-param-util.h.
 { return GetTypeId<TestSuite>(); }
Referenced by testing::internal::ParameterizedTestSuiteInfo< TestSuite >::RegisterTests().
GTEST_DISALLOW_COPY_AND_ASSIGN_()
template<class TestSuite > testing::internal::ParameterizedTestSuiteInfo< TestSuite >::GTEST_DISALLOW_COPY_AND_ASSIGN_ (ParameterizedTestSuiteInfo< TestSuite >) private
IsValidParamName()
template<class TestSuite > static bool testing::internal::ParameterizedTestSuiteInfo< TestSuite >::IsValidParamName (const std::string & name) inline static private
Definition at line 650 of file gtest-param-util.h.
{
     // Check for empty string
     if (name.empty())
       return false;
     // Check for invalid characters
     for (std::string::size_type index = 0; index < name.size(); ++index) {
       if (!isalnum(name[index]) && name[index] != '_')
         return false;
     }
     return true;
   }
Referenced by testing::internal::ParameterizedTestSuiteInfo< TestSuite >::RegisterTests().
ParamGenerator()
template<class TestSuite > typedef testing::internal::ParameterizedTestSuiteInfo< TestSuite >::ParamGenerator (GeneratorCreationFunc)
RegisterTests()
template<class TestSuite > void testing::internal::ParameterizedTestSuiteInfo< TestSuite >::RegisterTests () inline override virtual
Implements testing::internal::ParameterizedTestSuiteInfoBase.
Definition at line 543 of file gtest-param-util.h.
{
     bool generated_instantiations = false;
     for (typename TestInfoContainer::iterator test_it = tests_.begin();
          test_it != tests_.end(); ++test_it) {
       std::shared_ptr<TestInfo> test_info = *test_it;
       for (typename InstantiationContainer::iterator gen_it =
                instantiations_.begin(); gen_it != instantiations_.end();
                ++gen_it) {
         const std::string& instantiation_name = gen_it->name;
         ParamGenerator<ParamType> generator((*gen_it->generator)());
         ParamNameGeneratorFunc* name_func = gen_it->name_func;
         const char* file = gen_it->file;
         int line = gen_it->line;
         std::string test_suite_name;
         if ( !instantiation_name.empty() )
           test_suite_name = instantiation_name + "/";
         test_suite_name += test_info->test_suite_base_name;
         size_t i = 0;
         std::set<std::string> test_param_names;
         for (typename ParamGenerator<ParamType>::iterator param_it =
                  generator.begin();
              param_it != generator.end(); ++param_it, ++i) {
           generated_instantiations = true;
           Message test_name_stream;
           std::string param_name = name_func(
               TestParamInfo<ParamType>(*param_it, i));
           GTEST_CHECK_(IsValidParamName(param_name))
               << "Parameterized test name '" << param_name
               << "' is invalid, in " << file
               << " line " << line << std::endl;
           GTEST_CHECK_(test_param_names.count(param_name) == 0)
               << "Duplicate parameterized test name '" << param_name
               << "', in " << file << " line " << line << std::endl;
           test_param_names.insert(param_name);
           if (!test_info->test_base_name.empty()) {
             test_name_stream << test_info->test_base_name << "/";
           }
           test_name_stream << param_name;
           MakeAndRegisterTestInfo(
               test_suite_name.c_str(), test_name_stream.GetString().c_str(),
               nullptr,  // No type parameter.
               PrintToString(*param_it).c_str(), test_info->code_location,
               GetTestSuiteTypeId(),
               SuiteApiResolver<TestSuite>::GetSetUpCaseOrSuite(file, line),
               SuiteApiResolver<TestSuite>::GetTearDownCaseOrSuite(file, line),
               test_info->test_meta_factory->CreateTestFactory(*param_it));
         }  // for param_it
       }  // for gen_it
     }  // for test_it
     if (!generated_instantiations) {
       // There are no generaotrs, or they all generate nothing ...
       InsertSyntheticTestCase(GetTestSuiteName(), code_location_,
                               !tests_.empty());
     }
   }    // RegisterTests
References testing::internal::ParameterizedTestSuiteInfo< TestSuite >::TestInfo::code_location, testing::internal::ParameterizedTestSuiteInfo< TestSuite >::code_location_, testing::Message::GetString(), testing::internal::ParameterizedTestSuiteInfo< TestSuite >::GetTestSuiteName(), testing::internal::ParameterizedTestSuiteInfo< TestSuite >::GetTestSuiteTypeId(), GTEST_CHECK_, testing::internal::InsertSyntheticTestCase(), testing::internal::ParameterizedTestSuiteInfo< TestSuite >::instantiations_, testing::internal::ParameterizedTestSuiteInfo< TestSuite >::IsValidParamName(), testing::internal::MakeAndRegisterTestInfo(), testing::PrintToString(), testing::internal::ParameterizedTestSuiteInfo< TestSuite >::TestInfo::test_base_name, testing::internal::ParameterizedTestSuiteInfo< TestSuite >::TestInfo::test_meta_factory, testing::internal::ParameterizedTestSuiteInfo< TestSuite >::TestInfo::test_suite_base_name, and testing::internal::ParameterizedTestSuiteInfo< TestSuite >::tests_.
Member Data Documentation
code_location_
template<class TestSuite > CodeLocation testing::internal::ParameterizedTestSuiteInfo< TestSuite >::code_location_ private
Definition at line 665 of file gtest-param-util.h.
Referenced by testing::internal::ParameterizedTestSuiteInfo< TestSuite >::RegisterTests().
instantiations_
template<class TestSuite > InstantiationContainer testing::internal::ParameterizedTestSuiteInfo< TestSuite >::instantiations_ private
Definition at line 667 of file gtest-param-util.h.
Referenced by testing::internal::ParameterizedTestSuiteInfo< TestSuite >::AddTestSuiteInstantiation(), and testing::internal::ParameterizedTestSuiteInfo< TestSuite >::RegisterTests().
test_suite_name_
template<class TestSuite > const std::string testing::internal::ParameterizedTestSuiteInfo< TestSuite >::test_suite_name_ private
Definition at line 664 of file gtest-param-util.h.
Referenced by testing::internal::ParameterizedTestSuiteInfo< TestSuite >::GetTestSuiteName().
tests_
template<class TestSuite > TestInfoContainer testing::internal::ParameterizedTestSuiteInfo< TestSuite >::tests_ private
Definition at line 666 of file gtest-param-util.h.
Referenced by testing::internal::ParameterizedTestSuiteInfo< TestSuite >::AddTestPattern(), and testing::internal::ParameterizedTestSuiteInfo< TestSuite >::RegisterTests().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/internal/gtest-param-util.h