otus_cpp_print_ip: testing::internal::RangeGenerator< T, IncrementT >::Iterator Class Reference
testing::internal::RangeGenerator< T, IncrementT >::Iterator Class Reference
Public Member Functions
Iterator (const ParamGeneratorInterface< T > *base, T value, int index, IncrementT step)
~Iterator () override
const ParamGeneratorInterface< T > * BaseGenerator () const override
void Advance () override
ParamIteratorInterface< T > * Clone () const override
const T * Current () const override
bool Equals (const ParamIteratorInterface< T > &other) const override
Public Member Functions inherited from testing::internal::ParamIteratorInterface< T >
virtual ~ParamIteratorInterface ()
Private Member Functions
Iterator (const Iterator &other)
void operator= (const Iterator &other)
Private Attributes
const ParamGeneratorInterface< T > *const base_
T value_
int index_
const IncrementT step_
Detailed Description
template<typename T, typename IncrementT>
class testing::internal::RangeGenerator< T, IncrementT >::Iterator
Definition at line 222 of file gtest-param-util.h.
Constructor & Destructor Documentation
Iterator() [1/2]
template<typename T , typename IncrementT > testing::internal::RangeGenerator< T, IncrementT >::Iterator::Iterator (const ParamGeneratorInterface< T > * base, T value, int index, IncrementT step) inline
Definition at line 224 of file gtest-param-util.h.
         : base_(base), value_(value), index_(index), step_(step) {}
Referenced by testing::internal::RangeGenerator< T, IncrementT >::Iterator::Clone().
~Iterator()
template<typename T , typename IncrementT > testing::internal::RangeGenerator< T, IncrementT >::Iterator::~Iterator () inline override
Definition at line 227 of file gtest-param-util.h.
 {}
Iterator() [2/2]
template<typename T , typename IncrementT > testing::internal::RangeGenerator< T, IncrementT >::Iterator::Iterator (const Iterator & other) inline private
Definition at line 252 of file gtest-param-util.h.
         : ParamIteratorInterface<T>(),
           base_(other.base_), value_(other.value_), index_(other.index_),
           step_(other.step_) {}
Member Function Documentation
Advance()
template<typename T , typename IncrementT > void testing::internal::RangeGenerator< T, IncrementT >::Iterator::Advance () inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 232 of file gtest-param-util.h.
{
       value_ = static_cast<T>(value_ + step_);
       index_++;
     }
References testing::internal::RangeGenerator< T, IncrementT >::Iterator::index_, testing::internal::RangeGenerator< T, IncrementT >::Iterator::step_, and testing::internal::RangeGenerator< T, IncrementT >::Iterator::value_.
BaseGenerator()
template<typename T , typename IncrementT > const ParamGeneratorInterface<T>* testing::internal::RangeGenerator< T, IncrementT >::Iterator::BaseGenerator () const inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 229 of file gtest-param-util.h.
{
       return base_;
     }
References testing::internal::RangeGenerator< T, IncrementT >::Iterator::base_.
Referenced by testing::internal::RangeGenerator< T, IncrementT >::Iterator::Equals().
Clone()
template<typename T , typename IncrementT > ParamIteratorInterface<T>* testing::internal::RangeGenerator< T, IncrementT >::Iterator::Clone () const inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 236 of file gtest-param-util.h.
{
       return new Iterator(*this);
     }
References testing::internal::RangeGenerator< T, IncrementT >::Iterator::Iterator().
Current()
template<typename T , typename IncrementT > const T* testing::internal::RangeGenerator< T, IncrementT >::Iterator::Current () const inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 239 of file gtest-param-util.h.
 { return &value_; }
References testing::internal::RangeGenerator< T, IncrementT >::Iterator::value_.
Equals()
template<typename T , typename IncrementT > bool testing::internal::RangeGenerator< T, IncrementT >::Iterator::Equals (const ParamIteratorInterface< T > & other) const inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 240 of file gtest-param-util.h.
{
       // Having the same base generator guarantees that the other
       // iterator is of the same type and we can downcast.
       GTEST_CHECK_(BaseGenerator() == other.BaseGenerator())
           << "The program attempted to compare iterators "
           << "from different generators." << std::endl;
       const int other_index =
           CheckedDowncastToActualType<const Iterator>(&other)->index_;
       return index_ == other_index;
     }
References testing::internal::ParamIteratorInterface< T >::BaseGenerator(), testing::internal::RangeGenerator< T, IncrementT >::Iterator::BaseGenerator(), GTEST_CHECK_, and testing::internal::RangeGenerator< T, IncrementT >::Iterator::index_.
operator=()
template<typename T , typename IncrementT > void testing::internal::RangeGenerator< T, IncrementT >::Iterator::operator= (const Iterator & other) private
Member Data Documentation
base_
template<typename T , typename IncrementT > const ParamGeneratorInterface<T>* const testing::internal::RangeGenerator< T, IncrementT >::Iterator::base_ private
Definition at line 260 of file gtest-param-util.h.
Referenced by testing::internal::RangeGenerator< T, IncrementT >::Iterator::BaseGenerator().
index_
template<typename T , typename IncrementT > int testing::internal::RangeGenerator< T, IncrementT >::Iterator::index_ private
Definition at line 262 of file gtest-param-util.h.
Referenced by testing::internal::RangeGenerator< T, IncrementT >::Iterator::Advance(), and testing::internal::RangeGenerator< T, IncrementT >::Iterator::Equals().
step_
template<typename T , typename IncrementT > const IncrementT testing::internal::RangeGenerator< T, IncrementT >::Iterator::step_ private
Definition at line 263 of file gtest-param-util.h.
Referenced by testing::internal::RangeGenerator< T, IncrementT >::Iterator::Advance().
value_
template<typename T , typename IncrementT > T testing::internal::RangeGenerator< T, IncrementT >::Iterator::value_ private
Definition at line 261 of file gtest-param-util.h.
Referenced by testing::internal::RangeGenerator< T, IncrementT >::Iterator::Advance(), and testing::internal::RangeGenerator< T, IncrementT >::Iterator::Current().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/internal/gtest-param-util.h