otus_cpp_print_ip: testing::Message Class Reference
testing::Message Class Reference
#include <gtest-message.h>
Public Member Functions
Message ()
Message (const Message &msg)
Message (const char *str)
template<typename T >
Message & operator<< (const T &val)
template<typename T >
Message & operator<< (T *const &pointer)
Message & operator<< (BasicNarrowIoManip val)
Message & operator<< (bool b)
Message & operator<< (const wchar_t *wide_c_str)
Message & operator<< (wchar_t *wide_c_str)
std::string GetString () const
Private Types
typedef std::ostream &(* BasicNarrowIoManip) (std::ostream &)
Private Member Functions
void operator= (const Message &)
Private Attributes
const std::unique_ptr< ::std::stringstream > ss_
Detailed Description
Definition at line 91 of file gtest-message.h.
Member Typedef Documentation
BasicNarrowIoManip
typedef std::ostream&(* testing::Message::BasicNarrowIoManip) (std::ostream &) private
Definition at line 95 of file gtest-message.h.
Constructor & Destructor Documentation
Message() [1/3]
testing::Message::Message ()
Message() [2/3]
testing::Message::Message (const Message & msg) inline
Definition at line 102 of file gtest-message.h.
                               : ss_(new ::std::stringstream) {  // NOLINT
     *ss_ << msg.GetString();
   }
References GetString().
Message() [3/3]
testing::Message::Message (const char * str) inline explicit
Definition at line 107 of file gtest-message.h.
                                     : ss_(new ::std::stringstream) {
     *ss_ << str;
   }
Member Function Documentation
GetString()
std::string testing::Message::GetString () const
Referenced by testing::internal::DefaultParamName(), Message(), testing::operator<<(), and testing::internal::ParameterizedTestSuiteInfo< TestSuite >::RegisterTests().
operator<<() [1/6]
Message& testing::Message::operator<< (BasicNarrowIoManip val) inline
Definition at line 162 of file gtest-message.h.
{
     *ss_ << val;
     return *this;
   }
operator<<() [2/6]
Message& testing::Message::operator<< (bool b) inline
Definition at line 168 of file gtest-message.h.
{
     return *this << (b ? "true" : "false");
   }
operator<<() [3/6]
template<typename T > Message& testing::Message::operator<< (const T & val) inline
Definition at line 113 of file gtest-message.h.
{
     // Some libraries overload << for STL containers.  These
     // overloads are defined in the global namespace instead of ::std.
     //
     // C++'s symbol lookup rule (i.e. Koenig lookup) says that these
     // overloads are visible in either the std namespace or the global
     // namespace, but not other namespaces, including the testing
     // namespace which Google Test's Message class is in.
     //
     // To allow STL containers (and other types that has a << operator
     // defined in the global namespace) to be used in Google Test
     // assertions, testing::Message must access the custom << operator
     // from the global namespace.  With this using declaration,
     // overloads of << defined in the global namespace and those
     // visible via Koenig lookup are both exposed in this function.
     using ::operator <<;
     *ss_ << val;
     return *this;
   }
operator<<() [4/6]
Message& testing::Message::operator<< (const wchar_t * wide_c_str)
operator<<() [5/6]
template<typename T > Message& testing::Message::operator<< (T *const & pointer) inline
Definition at line 147 of file gtest-message.h.
                                                  {  // NOLINT
     if (pointer == nullptr) {
       *ss_ << "(null)";
     } else {
       *ss_ << pointer;
     }
     return *this;
   }
operator<<() [6/6]
Message& testing::Message::operator<< (wchar_t * wide_c_str)
operator=()
void testing::Message::operator= (const Message &) private
Member Data Documentation
ss_
const std::unique_ptr< ::std::stringstream> testing::Message::ss_ private
Definition at line 191 of file gtest-message.h.
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/gtest-message.h