otus_cpp_print_ip: _deps/googletest-src/googlemock/test/gmock_link_test.h File Reference
gmock_link_test.h File Reference
#include "gmock/gmock.h"
#include <errno.h>
#include <iostream>
#include <vector>
#include "gtest/gtest.h"
#include "gtest/internal/gtest-port.h"
Classes
class Interface
class Mock
class InvokeHelper
class FieldHelper
Namespaces
anonymous_namespace{gmock_link_test.h}
Functions
TEST (LinkTest, TestReturnVoid)
TEST (LinkTest, TestReturn)
TEST (LinkTest, TestReturnNull)
TEST (LinkTest, TestReturnRef)
TEST (LinkTest, TestAssign)
TEST (LinkTest, TestSetArgPointee)
TEST (LinkTest, TestSetArrayArgument)
TEST (LinkTest, TestSetErrnoAndReturn)
TEST (LinkTest, TestInvoke)
TEST (LinkTest, TestInvokeWithoutArgs)
TEST (LinkTest, TestInvokeArgument)
TEST (LinkTest, TestWithArg)
TEST (LinkTest, TestWithArgs)
TEST (LinkTest, TestWithoutArgs)
TEST (LinkTest, TestDoAll)
TEST (LinkTest, TestDoDefault)
TEST (LinkTest, TestIgnoreResult)
anonymous_namespace{gmock_link_test.h}::ACTION (Return1)
TEST (LinkTest, TestActionMacro)
anonymous_namespace{gmock_link_test.h}::ACTION_P (ReturnArgument, ret_value)
TEST (LinkTest, TestActionPMacro)
anonymous_namespace{gmock_link_test.h}::ACTION_P2 (ReturnEqualsEitherOf, first, second)
TEST (LinkTest, TestActionP2Macro)
TEST (LinkTest, TestMatcherAnything)
TEST (LinkTest, TestMatcherA)
TEST (LinkTest, TestMatchersEq)
TEST (LinkTest, TestMatchersRelations)
TEST (LinkTest, TestMatcherNotNull)
TEST (LinkTest, TestMatcherIsNull)
TEST (LinkTest, TestMatcherRef)
TEST (LinkTest, TestMatcherTypedEq)
TEST (LinkTest, TestMatchersFloatingPoint)
TEST (LinkTest, TestMatcherContainsRegex)
TEST (LinkTest, TestMatcherMatchesRegex)
TEST (LinkTest, TestMatchersSubstrings)
TEST (LinkTest, TestMatchersStringEquality)
TEST (LinkTest, TestMatcherElementsAre)
TEST (LinkTest, TestMatcherElementsAreArray)
TEST (LinkTest, TestMatcherIsSubsetOf)
TEST (LinkTest, TestMatcherIsSupersetOf)
TEST (LinkTest, TestMatcherContainerEq)
TEST (LinkTest, TestMatcherField)
TEST (LinkTest, TestMatcherProperty)
TEST (LinkTest, TestMatcherResultOf)
TEST (LinkTest, TestMatcherPointee)
TEST (LinkTest, TestMatcherTruly)
TEST (LinkTest, TestMatcherAllOf)
TEST (LinkTest, TestMatcherAnyOf)
TEST (LinkTest, TestMatcherNot)
TEST (LinkTest, TestMatcherCast)
Function Documentation
TEST() [1/47]
TEST (LinkTest , TestActionMacro)
Definition at line 436 of file gmock_link_test.h.
{
   Mock mock;
   EXPECT_CALL(mock, IntFromString(_)).WillOnce(Return1());
   mock.IntFromString(nullptr);
 }
References EXPECT_CALL, and Interface::IntFromString().
TEST() [2/47]
TEST (LinkTest , TestActionP2Macro)
Definition at line 466 of file gmock_link_test.h.
{
   Mock mock;
   char ch = 'x';
   EXPECT_CALL(mock, IntFromString(_))
       .WillOnce(ReturnEqualsEitherOf("one", "two"));
   mock.IntFromString(&ch);
 }
References EXPECT_CALL, and Interface::IntFromString().
TEST() [3/47]
TEST (LinkTest , TestActionPMacro)
Definition at line 448 of file gmock_link_test.h.
{
   Mock mock;
   EXPECT_CALL(mock, IntFromString(_)).WillOnce(ReturnArgument(42));
   mock.IntFromString(nullptr);
 }
References EXPECT_CALL, and Interface::IntFromString().
TEST() [4/47]
TEST (LinkTest , TestAssign)
Definition at line 281 of file gmock_link_test.h.
{
   Mock mock;
   char ch = 'x';
   EXPECT_CALL(mock, VoidFromString(_)).WillOnce(Assign(&ch, 'y'));
   mock.VoidFromString(nullptr);
 }
References testing::Assign(), EXPECT_CALL, and Interface::VoidFromString().
TEST() [5/47]
TEST (LinkTest , TestDoAll)
Definition at line 384 of file gmock_link_test.h.
{
   Mock mock;
   char ch = 'x';
   EXPECT_CALL(mock, VoidFromString(_))
       .WillOnce(DoAll(SetArgPointee<0>('y'), Return()));
   mock.VoidFromString(&ch);
 }
References testing::DoAll(), EXPECT_CALL, testing::Return(), and Interface::VoidFromString().
TEST() [6/47]
TEST (LinkTest , TestDoDefault)
Definition at line 394 of file gmock_link_test.h.
{
   Mock mock;
   char ch = 'x';
   ON_CALL(mock, VoidFromString(_)).WillByDefault(Return());
   EXPECT_CALL(mock, VoidFromString(_)).WillOnce(DoDefault());
   mock.VoidFromString(&ch);
 }
References testing::DoDefault(), EXPECT_CALL, ON_CALL, testing::Return(), and Interface::VoidFromString().
TEST() [7/47]
TEST (LinkTest , TestIgnoreResult)
Definition at line 404 of file gmock_link_test.h.
{
   Mock mock;
   EXPECT_CALL(mock, VoidFromString(_)).WillOnce(IgnoreResult(Return(42)));
   mock.VoidFromString(nullptr);
 }
References EXPECT_CALL, testing::IgnoreResult(), testing::Return(), and Interface::VoidFromString().
TEST() [8/47]
TEST (LinkTest , TestInvoke)
Definition at line 324 of file gmock_link_test.h.
{
   Mock mock;
   InvokeHelper test_invoke_helper;
   EXPECT_CALL(mock, VoidFromString(_))
       .WillOnce(Invoke(&InvokeHelper::StaticVoidFromString))
       .WillOnce(Invoke(&test_invoke_helper, &InvokeHelper::VoidFromString));
   mock.VoidFromString(nullptr);
   mock.VoidFromString(nullptr);
 }
References EXPECT_CALL, testing::Invoke(), InvokeHelper::StaticVoidFromString(), Interface::VoidFromString(), and InvokeHelper::VoidFromString().
TEST() [9/47]
TEST (LinkTest , TestInvokeArgument)
Definition at line 349 of file gmock_link_test.h.
{
   Mock mock;
   char ch = 'x';
   EXPECT_CALL(mock, VoidFromFunc(_)).WillOnce(InvokeArgument<0>(&ch));
   mock.VoidFromFunc(InvokeHelper::StaticVoidFromString);
 }
References EXPECT_CALL, InvokeHelper::StaticVoidFromString(), and Interface::VoidFromFunc().
TEST() [10/47]
TEST (LinkTest , TestInvokeWithoutArgs)
Definition at line 336 of file gmock_link_test.h.
{
   Mock mock;
   InvokeHelper test_invoke_helper;
   EXPECT_CALL(mock, VoidFromString(_))
       .WillOnce(InvokeWithoutArgs(&InvokeHelper::StaticVoidFromVoid))
       .WillOnce(InvokeWithoutArgs(&test_invoke_helper,
                                   &InvokeHelper::VoidFromVoid));
   mock.VoidFromString(nullptr);
   mock.VoidFromString(nullptr);
 }
References EXPECT_CALL, testing::InvokeWithoutArgs(), InvokeHelper::StaticVoidFromVoid(), Interface::VoidFromString(), and InvokeHelper::VoidFromVoid().
TEST() [11/47]
TEST (LinkTest , TestMatcherA)
Definition at line 483 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromString(A<char*>())).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [12/47]
TEST (LinkTest , TestMatcherAllOf)
Definition at line 667 of file gmock_link_test.h.
{
   Matcher<int> m = AllOf(_, Eq(1));
   EXPECT_TRUE(m.Matches(1));
 }
References EXPECT_TRUE.
TEST() [13/47]
TEST (LinkTest , TestMatcherAnyOf)
Definition at line 673 of file gmock_link_test.h.
{
   Matcher<int> m = AnyOf(_, Eq(1));
   EXPECT_TRUE(m.Matches(1));
 }
References EXPECT_TRUE.
TEST() [14/47]
TEST (LinkTest , TestMatcherAnything)
Definition at line 476 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromString(_)).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [15/47]
TEST (LinkTest , TestMatcherCast)
Definition at line 685 of file gmock_link_test.h.
{
   Matcher<const char*> m = MatcherCast<const char*>(_);
   EXPECT_TRUE(m.Matches(nullptr));
 }
References EXPECT_TRUE.
TEST() [16/47]
TEST (LinkTest , TestMatcherContainerEq)
Definition at line 617 of file gmock_link_test.h.
{
   Mock mock;
   std::vector<int> v;
   ON_CALL(mock, VoidFromVector(ContainerEq(v))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [17/47]
TEST (LinkTest , TestMatcherContainsRegex)
Definition at line 554 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromString(ContainsRegex(".*"))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [18/47]
TEST (LinkTest , TestMatcherElementsAre)
Definition at line 586 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromVector(ElementsAre('a', _))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [19/47]
TEST (LinkTest , TestMatcherElementsAreArray)
Definition at line 593 of file gmock_link_test.h.
{
   Mock mock;
   char arr[] = { 'a', 'b' };
   ON_CALL(mock, VoidFromVector(ElementsAreArray(arr))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [20/47]
TEST (LinkTest , TestMatcherField)
Definition at line 625 of file gmock_link_test.h.
{
   FieldHelper helper(0);
   Matcher<const FieldHelper&> m = Field(&FieldHelper::field_, Eq(0));
   EXPECT_TRUE(m.Matches(helper));
   Matcher<const FieldHelper*> m2 = Field(&FieldHelper::field_, Eq(0));
   EXPECT_TRUE(m2.Matches(&helper));
 }
References EXPECT_TRUE, and FieldHelper::field_.
TEST() [21/47]
TEST (LinkTest , TestMatcherIsNull)
Definition at line 518 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromString(IsNull())).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [22/47]
TEST (LinkTest , TestMatcherIsSubsetOf)
Definition at line 601 of file gmock_link_test.h.
{
   Mock mock;
   char arr[] = {'a', 'b'};
   ON_CALL(mock, VoidFromVector(IsSubsetOf(arr))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [23/47]
TEST (LinkTest , TestMatcherIsSupersetOf)
Definition at line 609 of file gmock_link_test.h.
{
   Mock mock;
   char arr[] = {'a', 'b'};
   ON_CALL(mock, VoidFromVector(IsSupersetOf(arr))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [24/47]
TEST (LinkTest , TestMatcherMatchesRegex)
Definition at line 561 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromString(MatchesRegex(".*"))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [25/47]
TEST (LinkTest , TestMatcherNot)
Definition at line 679 of file gmock_link_test.h.
{
   Matcher<int> m = Not(_);
   EXPECT_FALSE(m.Matches(1));
 }
References EXPECT_FALSE.
TEST() [26/47]
TEST (LinkTest , TestMatcherNotNull)
Definition at line 511 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromString(NotNull())).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [27/47]
TEST (LinkTest , TestMatcherPointee)
Definition at line 653 of file gmock_link_test.h.
{
   int n = 1;
   Matcher<int*> m = Pointee(Eq(1));
   EXPECT_TRUE(m.Matches(&n));
 }
References EXPECT_TRUE.
TEST() [28/47]
TEST (LinkTest , TestMatcherProperty)
Definition at line 636 of file gmock_link_test.h.
{
   FieldHelper helper(0);
   Matcher<const FieldHelper&> m = Property(&FieldHelper::field, Eq(0));
   EXPECT_TRUE(m.Matches(helper));
   Matcher<const FieldHelper*> m2 = Property(&FieldHelper::field, Eq(0));
   EXPECT_TRUE(m2.Matches(&helper));
 }
References EXPECT_TRUE, and FieldHelper::field().
TEST() [29/47]
TEST (LinkTest , TestMatcherRef)
Definition at line 525 of file gmock_link_test.h.
{
   Mock mock;
   int a = 0;
   ON_CALL(mock, VoidFromIntRef(Ref(a))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [30/47]
TEST (LinkTest , TestMatcherResultOf)
Definition at line 647 of file gmock_link_test.h.
{
   Matcher<char*> m = ResultOf(&InvokeHelper::StaticIntFromString, Eq(1));
   EXPECT_TRUE(m.Matches(nullptr));
 }
References EXPECT_TRUE, and InvokeHelper::StaticIntFromString().
TEST() [31/47]
TEST (LinkTest , TestMatchersEq)
Definition at line 490 of file gmock_link_test.h.
{
   Mock mock;
   const char* p = "x";
   ON_CALL(mock, VoidFromString(Eq(p))).WillByDefault(Return());
   ON_CALL(mock, VoidFromString(const_cast<char*>("y")))
       .WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [32/47]
TEST (LinkTest , TestMatchersFloatingPoint)
Definition at line 542 of file gmock_link_test.h.
{
   Mock mock;
   float a = 0;
   ON_CALL(mock, VoidFromFloat(FloatEq(a))).WillByDefault(Return());
   ON_CALL(mock, VoidFromDouble(DoubleEq(a))).WillByDefault(Return());
   ON_CALL(mock, VoidFromFloat(NanSensitiveFloatEq(a))).WillByDefault(Return());
   ON_CALL(mock, VoidFromDouble(NanSensitiveDoubleEq(a)))
       .WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [33/47]
TEST (LinkTest , TestMatchersRelations)
Definition at line 500 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromFloat(Lt(1.0f))).WillByDefault(Return());
   ON_CALL(mock, VoidFromFloat(Gt(1.0f))).WillByDefault(Return());
   ON_CALL(mock, VoidFromFloat(Le(1.0f))).WillByDefault(Return());
   ON_CALL(mock, VoidFromFloat(Ge(1.0f))).WillByDefault(Return());
   ON_CALL(mock, VoidFromFloat(Ne(1.0f))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [34/47]
TEST (LinkTest , TestMatchersStringEquality)
Definition at line 577 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromString(StrEq("a"))).WillByDefault(Return());
   ON_CALL(mock, VoidFromString(StrNe("a"))).WillByDefault(Return());
   ON_CALL(mock, VoidFromString(StrCaseEq("a"))).WillByDefault(Return());
   ON_CALL(mock, VoidFromString(StrCaseNe("a"))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [35/47]
TEST (LinkTest , TestMatchersSubstrings)
Definition at line 568 of file gmock_link_test.h.
{
   Mock mock;
   ON_CALL(mock, VoidFromString(StartsWith("a"))).WillByDefault(Return());
   ON_CALL(mock, VoidFromString(EndsWith("c"))).WillByDefault(Return());
   ON_CALL(mock, VoidFromString(HasSubstr("b"))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [36/47]
TEST (LinkTest , TestMatcherTruly)
Definition at line 661 of file gmock_link_test.h.
{
   Matcher<const char*> m = Truly(&InvokeHelper::StaticBoolFromString);
   EXPECT_TRUE(m.Matches(nullptr));
 }
References EXPECT_TRUE, and InvokeHelper::StaticBoolFromString().
TEST() [37/47]
TEST (LinkTest , TestMatcherTypedEq)
Definition at line 533 of file gmock_link_test.h.
{
   Mock mock;
   long a = 0;
   ON_CALL(mock, VoidFromIntRef(TypedEq<int&>(a))).WillByDefault(Return());
 }
References ON_CALL, and testing::Return().
TEST() [38/47]
TEST (LinkTest , TestReturn)
Definition at line 255 of file gmock_link_test.h.
{
   Mock mock;
   char ch = 'x';
   EXPECT_CALL(mock, StringFromString(_)).WillOnce(Return(&ch));
   mock.StringFromString(nullptr);
 }
References EXPECT_CALL, testing::Return(), and Interface::StringFromString().
TEST() [39/47]
TEST (LinkTest , TestReturnNull)
Definition at line 264 of file gmock_link_test.h.
{
   Mock mock;
   EXPECT_CALL(mock, VoidFromString(_)).WillOnce(Return());
   mock.VoidFromString(nullptr);
 }
References EXPECT_CALL, testing::Return(), and Interface::VoidFromString().
TEST() [40/47]
TEST (LinkTest , TestReturnRef)
Definition at line 272 of file gmock_link_test.h.
{
   Mock mock;
   int n = 42;
   EXPECT_CALL(mock, IntRefFromString(_)).WillOnce(ReturnRef(n));
   mock.IntRefFromString(nullptr);
 }
References EXPECT_CALL, Interface::IntRefFromString(), and testing::ReturnRef().
TEST() [41/47]
TEST (LinkTest , TestReturnVoid)
Definition at line 247 of file gmock_link_test.h.
{
   Mock mock;
   EXPECT_CALL(mock, VoidFromString(_)).WillOnce(Return());
   mock.VoidFromString(nullptr);
 }
References EXPECT_CALL, testing::Return(), and Interface::VoidFromString().
TEST() [42/47]
TEST (LinkTest , TestSetArgPointee)
Definition at line 290 of file gmock_link_test.h.
{
   Mock mock;
   char ch = 'x';
   EXPECT_CALL(mock, VoidFromString(_)).WillOnce(SetArgPointee<0>('y'));
   mock.VoidFromString(&ch);
 }
References EXPECT_CALL, and Interface::VoidFromString().
TEST() [43/47]
TEST (LinkTest , TestSetArrayArgument)
Definition at line 299 of file gmock_link_test.h.
{
   Mock mock;
   char ch = 'x';
   char ch2 = 'y';
   EXPECT_CALL(mock, VoidFromString(_)).WillOnce(SetArrayArgument<0>(&ch2,
                                                                     &ch2 + 1));
   mock.VoidFromString(&ch);
 }
References EXPECT_CALL, and Interface::VoidFromString().
TEST() [44/47]
TEST (LinkTest , TestSetErrnoAndReturn)
Definition at line 312 of file gmock_link_test.h.
{
   Mock mock;
   int saved_errno = errno;
   EXPECT_CALL(mock, IntFromString(_)).WillOnce(SetErrnoAndReturn(1, -1));
   mock.IntFromString(nullptr);
   errno = saved_errno;
 }
References EXPECT_CALL, Interface::IntFromString(), and testing::SetErrnoAndReturn().
TEST() [45/47]
TEST (LinkTest , TestWithArg)
Definition at line 358 of file gmock_link_test.h.
{
   Mock mock;
   EXPECT_CALL(mock, VoidFromString(_))
       .WillOnce(WithArg<0>(Invoke(&InvokeHelper::StaticVoidFromString)));
   mock.VoidFromString(nullptr);
 }
References EXPECT_CALL, testing::Invoke(), InvokeHelper::StaticVoidFromString(), and Interface::VoidFromString().
TEST() [46/47]
TEST (LinkTest , TestWithArgs)
Definition at line 367 of file gmock_link_test.h.
{
   Mock mock;
   EXPECT_CALL(mock, VoidFromString(_))
       .WillOnce(WithArgs<0>(Invoke(&InvokeHelper::StaticVoidFromString)));
   mock.VoidFromString(nullptr);
 }
References EXPECT_CALL, testing::Invoke(), InvokeHelper::StaticVoidFromString(), and Interface::VoidFromString().
TEST() [47/47]
TEST (LinkTest , TestWithoutArgs)
Definition at line 376 of file gmock_link_test.h.
{
   Mock mock;
   EXPECT_CALL(mock, VoidFromString(_)).WillOnce(WithoutArgs(Return()));
   mock.VoidFromString(nullptr);
 }
References EXPECT_CALL, testing::Return(), Interface::VoidFromString(), and testing::WithoutArgs().