otus_cpp_print_ip: testing::TestSuite Class Reference
testing::TestSuite Class Reference
#include <gtest.h>
Public Member Functions
TestSuite (const char *name, const char *a_type_param, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc)
virtual ~TestSuite ()
const char * name () const
const char * type_param () const
bool should_run () const
int successful_test_count () const
int skipped_test_count () const
int failed_test_count () const
int reportable_disabled_test_count () const
int disabled_test_count () const
int reportable_test_count () const
int test_to_run_count () const
int total_test_count () const
bool Passed () const
bool Failed () const
TimeInMillis elapsed_time () const
TimeInMillis start_timestamp () const
const TestInfo * GetTestInfo (int i) const
const TestResult & ad_hoc_test_result () const
Private Member Functions
std::vector< TestInfo * > & test_info_list ()
const std::vector< TestInfo * > & test_info_list () const
TestInfo * GetMutableTestInfo (int i)
void set_should_run (bool should)
void AddTestInfo (TestInfo *test_info)
void ClearResult ()
void Run ()
void Skip ()
void RunSetUpTestSuite ()
void RunTearDownTestSuite ()
void ShuffleTests (internal::Random *random)
void UnshuffleTests ()
GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestSuite)
Static Private Member Functions
static void ClearTestSuiteResult (TestSuite *test_suite)
static bool TestPassed (const TestInfo *test_info)
static bool TestSkipped (const TestInfo *test_info)
static bool TestFailed (const TestInfo *test_info)
static bool TestReportableDisabled (const TestInfo *test_info)
static bool TestDisabled (const TestInfo *test_info)
static bool TestReportable (const TestInfo *test_info)
static bool ShouldRunTest (const TestInfo *test_info)
Private Attributes
std::string name_
const std::unique_ptr< const ::std::string > type_param_
std::vector< TestInfo * > test_info_list_
std::vector< int > test_indices_
internal::SetUpTestSuiteFunc set_up_tc_
internal::TearDownTestSuiteFunc tear_down_tc_
bool should_run_
TimeInMillis start_timestamp_
TimeInMillis elapsed_time_
TestResult ad_hoc_test_result_
Friends
class Test
class internal::UnitTestImpl
Detailed Description
Definition at line 842 of file gtest.h.
Constructor & Destructor Documentation
TestSuite()
testing::TestSuite::TestSuite (const char * name, const char * a_type_param, internal::SetUpTestSuiteFunc set_up_tc, internal::TearDownTestSuiteFunc tear_down_tc)
~TestSuite()
virtual testing::TestSuite::~TestSuite () virtual
Member Function Documentation
ad_hoc_test_result()
const TestResult& testing::TestSuite::ad_hoc_test_result () const inline
Definition at line 921 of file gtest.h.
 { return ad_hoc_test_result_; }
AddTestInfo()
void testing::TestSuite::AddTestInfo (TestInfo * test_info) private
ClearResult()
void testing::TestSuite::ClearResult () private
Referenced by ClearTestSuiteResult().
ClearTestSuiteResult()
static void testing::TestSuite::ClearTestSuiteResult (TestSuite * test_suite) inline static private
Definition at line 950 of file gtest.h.
{
     test_suite->ClearResult();
   }
References ClearResult().
disabled_test_count()
int testing::TestSuite::disabled_test_count () const
elapsed_time()
TimeInMillis testing::TestSuite::elapsed_time () const inline
Definition at line 909 of file gtest.h.
 { return elapsed_time_; }
Failed()
bool testing::TestSuite::Failed () const inline
Definition at line 904 of file gtest.h.
                       {
     return failed_test_count() > 0 || ad_hoc_test_result().Failed();
   }
failed_test_count()
int testing::TestSuite::failed_test_count () const
GetMutableTestInfo()
TestInfo* testing::TestSuite::GetMutableTestInfo (int i) private
GetTestInfo()
const TestInfo* testing::TestSuite::GetTestInfo (int i) const
GTEST_DISALLOW_COPY_AND_ASSIGN_()
testing::TestSuite::GTEST_DISALLOW_COPY_AND_ASSIGN_ (TestSuite) private
name()
const char* testing::TestSuite::name () const inline
Definition at line 864 of file gtest.h.
 { return name_.c_str(); }
Passed()
bool testing::TestSuite::Passed () const inline
Definition at line 901 of file gtest.h.
 { return !Failed(); }
reportable_disabled_test_count()
int testing::TestSuite::reportable_disabled_test_count () const
reportable_test_count()
int testing::TestSuite::reportable_test_count () const
Run()
void testing::TestSuite::Run () private
RunSetUpTestSuite()
void testing::TestSuite::RunSetUpTestSuite () inline private
Definition at line 962 of file gtest.h.
{
     if (set_up_tc_ != nullptr) {
       (*set_up_tc_)();
     }
   }
RunTearDownTestSuite()
void testing::TestSuite::RunTearDownTestSuite () inline private
Definition at line 970 of file gtest.h.
{
     if (tear_down_tc_ != nullptr) {
       (*tear_down_tc_)();
     }
   }
set_should_run()
void testing::TestSuite::set_should_run (bool should) inline private
Definition at line 940 of file gtest.h.
 { should_run_ = should; }
should_run()
bool testing::TestSuite::should_run () const inline
Definition at line 874 of file gtest.h.
 { return should_run_; }
ShouldRunTest()
static bool testing::TestSuite::ShouldRunTest (const TestInfo * test_info) inline static private
Definition at line 1008 of file gtest.h.
{
     return test_info->should_run();
   }
References testing::TestInfo::should_run().
ShuffleTests()
void testing::TestSuite::ShuffleTests (internal::Random * random) private
Skip()
void testing::TestSuite::Skip () private
skipped_test_count()
int testing::TestSuite::skipped_test_count () const
start_timestamp()
TimeInMillis testing::TestSuite::start_timestamp () const inline
Definition at line 913 of file gtest.h.
 { return start_timestamp_; }
successful_test_count()
int testing::TestSuite::successful_test_count () const
test_info_list() [1/2]
std::vector<TestInfo*>& testing::TestSuite::test_info_list () inline private
Definition at line 928 of file gtest.h.
 { return test_info_list_; }
test_info_list() [2/2]
const std::vector<TestInfo*>& testing::TestSuite::test_info_list () const inline private
Definition at line 931 of file gtest.h.
{
     return test_info_list_;
   }
test_to_run_count()
int testing::TestSuite::test_to_run_count () const
TestDisabled()
static bool testing::TestSuite::TestDisabled (const TestInfo * test_info) inline static private
Definition at line 998 of file gtest.h.
{
     return test_info->is_disabled_;
   }
References testing::TestInfo::is_disabled_.
TestFailed()
static bool testing::TestSuite::TestFailed (const TestInfo * test_info) inline static private
Definition at line 987 of file gtest.h.
{
     return test_info->should_run() && test_info->result()->Failed();
   }
References testing::TestResult::Failed(), testing::TestInfo::result(), and testing::TestInfo::should_run().
TestPassed()
static bool testing::TestSuite::TestPassed (const TestInfo * test_info) inline static private
Definition at line 977 of file gtest.h.
{
     return test_info->should_run() && test_info->result()->Passed();
   }
References testing::TestResult::Passed(), testing::TestInfo::result(), and testing::TestInfo::should_run().
TestReportable()
static bool testing::TestSuite::TestReportable (const TestInfo * test_info) inline static private
Definition at line 1003 of file gtest.h.
{
     return test_info->is_reportable();
   }
References testing::TestInfo::is_reportable().
TestReportableDisabled()
static bool testing::TestSuite::TestReportableDisabled (const TestInfo * test_info) inline static private
Definition at line 993 of file gtest.h.
{
     return test_info->is_reportable() && test_info->is_disabled_;
   }
References testing::TestInfo::is_disabled_, and testing::TestInfo::is_reportable().
TestSkipped()
static bool testing::TestSuite::TestSkipped (const TestInfo * test_info) inline static private
Definition at line 982 of file gtest.h.
{
     return test_info->should_run() && test_info->result()->Skipped();
   }
References testing::TestInfo::result(), testing::TestInfo::should_run(), and testing::TestResult::Skipped().
total_test_count()
int testing::TestSuite::total_test_count () const
type_param()
const char* testing::TestSuite::type_param () const inline
Definition at line 868 of file gtest.h.
{
     if (type_param_.get() != nullptr) return type_param_->c_str();
     return nullptr;
   }
UnshuffleTests()
void testing::TestSuite::UnshuffleTests () private
Friends And Related Function Documentation
internal::UnitTestImpl
friend class internal::UnitTestImpl friend
Definition at line 925 of file gtest.h.
Test
friend class Test friend
Definition at line 924 of file gtest.h.
Member Data Documentation
ad_hoc_test_result_
TestResult testing::TestSuite::ad_hoc_test_result_ private
Definition at line 1042 of file gtest.h.
elapsed_time_
TimeInMillis testing::TestSuite::elapsed_time_ private
Definition at line 1039 of file gtest.h.
name_
std::string testing::TestSuite::name_ private
Definition at line 1019 of file gtest.h.
set_up_tc_
internal::SetUpTestSuiteFunc testing::TestSuite::set_up_tc_ private
Definition at line 1031 of file gtest.h.
should_run_
bool testing::TestSuite::should_run_ private
Definition at line 1035 of file gtest.h.
start_timestamp_
TimeInMillis testing::TestSuite::start_timestamp_ private
Definition at line 1037 of file gtest.h.
tear_down_tc_
internal::TearDownTestSuiteFunc testing::TestSuite::tear_down_tc_ private
Definition at line 1033 of file gtest.h.
test_indices_
std::vector<int> testing::TestSuite::test_indices_ private
Definition at line 1029 of file gtest.h.
test_info_list_
std::vector<TestInfo*> testing::TestSuite::test_info_list_ private
Definition at line 1025 of file gtest.h.
type_param_
const std::unique_ptr<const ::std::string> testing::TestSuite::type_param_ private
Definition at line 1022 of file gtest.h.
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/gtest.h