otus_cpp_print_ip: testing::internal::DoAllAction< Actions > Struct Template Reference
testing::internal::DoAllAction< Actions > Struct Template Reference
#include <gmock-actions.h>
Public Member Functions
template<typename R , typename... Args>
operator Action< R (Args...)>() const
Public Attributes
std::tuple< Actions... > actions
Private Types
template<typename T >
using NonFinalType = typename std::conditional< std::is_scalar< T >::value, T, const T & >::type
Private Member Functions
template<typename ActionT , size_t... I>
std::vector< ActionT > Convert (IndexSequence< I... >) const
Detailed Description
template<typename... Actions>
struct testing::internal::DoAllAction< Actions >
Definition at line 1034 of file gmock-actions.h.
Member Typedef Documentation
NonFinalType
template<typename... Actions> template<typename T > using testing::internal::DoAllAction< Actions >::NonFinalType = typename std::conditional<std::is_scalar<T>::value, T, const T&>::type private
Definition at line 1038 of file gmock-actions.h.
Member Function Documentation
Convert()
template<typename... Actions> template<typename ActionT , size_t... I> std::vector<ActionT> testing::internal::DoAllAction< Actions >::Convert (IndexSequence< I... >) const inline private
Definition at line 1041 of file gmock-actions.h.
{
     return {ActionT(std::get<I>(actions))...};
   }
References testing::internal::DoAllAction< Actions >::actions.
Referenced by testing::internal::DoAllAction< Actions >::operator Action< R().
operator Action< R()
template<typename... Actions> template<typename R , typename... Args> testing::internal::DoAllAction< Actions >::operator Action< R (Args...) const inline
Definition at line 1049 of file gmock-actions.h.
                                       {  // NOLINT
     struct Op {
       std::vector<Action<void(NonFinalType<Args>...)>> converted;
       Action<R(Args...)> last;
       R operator()(Args... args) const {
         auto tuple_args = std::forward_as_tuple(std::forward<Args>(args)...);
         for (auto& a : converted) {
           a.Perform(tuple_args);
         }
         return last.Perform(std::move(tuple_args));
       }
     };
     return Op{Convert<Action<void(NonFinalType<Args>...)>>(
                   MakeIndexSequence<sizeof...(Actions) - 1>()),
               std::get<sizeof...(Actions) - 1>(actions)};
   }
References testing::internal::DoAllAction< Actions >::actions, testing::internal::DoAllAction< Actions >::Convert(), and testing::Action< F >::Perform().
Member Data Documentation
actions
template<typename... Actions> std::tuple<Actions...> testing::internal::DoAllAction< Actions >::actions
Definition at line 1046 of file gmock-actions.h.
Referenced by testing::internal::DoAllAction< Actions >::Convert(), and testing::internal::DoAllAction< Actions >::operator Action< R().
The documentation for this struct was generated from the following file:
_deps/googletest-src/googlemock/include/gmock/gmock-actions.h