otus_cpp_print_ip: testing::internal::SuiteApiResolver< T > Struct Template Reference
testing::internal::SuiteApiResolver< T > Struct Template Reference
#include <gtest-internal.h>
Public Types
using Test = typename std::conditional< sizeof(T) !=0, ::testing::Test, void >::type
Static Public Member Functions
static SetUpTearDownSuiteFuncType GetSetUpCaseOrSuite (const char *filename, int line_num)
static SetUpTearDownSuiteFuncType GetTearDownCaseOrSuite (const char *filename, int line_num)
Detailed Description
template<typename T>
struct testing::internal::SuiteApiResolver< T >
Definition at line 515 of file gtest-internal.h.
Member Typedef Documentation
Test
template<typename T > using testing::internal::SuiteApiResolver< T >::Test = typename std::conditional<sizeof(T) != 0, ::testing::Test, void>::type
Definition at line 519 of file gtest-internal.h.
Member Function Documentation
GetSetUpCaseOrSuite()
template<typename T > static SetUpTearDownSuiteFuncType testing::internal::SuiteApiResolver< T >::GetSetUpCaseOrSuite (const char * filename, int line_num) inline static
Definition at line 521 of file gtest-internal.h.
{
 #ifndef GTEST_REMOVE_LEGACY_TEST_CASEAPI_
     SetUpTearDownSuiteFuncType test_case_fp =
         GetNotDefaultOrNull(&T::SetUpTestCase, &Test::SetUpTestCase);
     SetUpTearDownSuiteFuncType test_suite_fp =
         GetNotDefaultOrNull(&T::SetUpTestSuite, &Test::SetUpTestSuite);
     GTEST_CHECK_(!test_case_fp || !test_suite_fp)
         << "Test can not provide both SetUpTestSuite and SetUpTestCase, please "
            "make sure there is only one present at "
         << filename << ":" << line_num;
     return test_case_fp != nullptr ? test_case_fp : test_suite_fp;
 #else
     (void)(filename);
     (void)(line_num);
     return &T::SetUpTestSuite;
 #endif
   }
References testing::internal::GetNotDefaultOrNull(), GTEST_CHECK_, testing::Test::SetUpTestCase(), and testing::Test::SetUpTestSuite().
GetTearDownCaseOrSuite()
template<typename T > static SetUpTearDownSuiteFuncType testing::internal::SuiteApiResolver< T >::GetTearDownCaseOrSuite (const char * filename, int line_num) inline static
Definition at line 542 of file gtest-internal.h.
{
 #ifndef GTEST_REMOVE_LEGACY_TEST_CASEAPI_
     SetUpTearDownSuiteFuncType test_case_fp =
         GetNotDefaultOrNull(&T::TearDownTestCase, &Test::TearDownTestCase);
     SetUpTearDownSuiteFuncType test_suite_fp =
         GetNotDefaultOrNull(&T::TearDownTestSuite, &Test::TearDownTestSuite);
     GTEST_CHECK_(!test_case_fp || !test_suite_fp)
         << "Test can not provide both TearDownTestSuite and TearDownTestCase,"
            " please make sure there is only one present at"
         << filename << ":" << line_num;
     return test_case_fp != nullptr ? test_case_fp : test_suite_fp;
 #else
     (void)(filename);
     (void)(line_num);
     return &T::TearDownTestSuite;
 #endif
   }
References testing::internal::GetNotDefaultOrNull(), GTEST_CHECK_, testing::Test::TearDownTestCase(), and testing::Test::TearDownTestSuite().
The documentation for this struct was generated from the following file:
_deps/googletest-src/googletest/include/gtest/internal/gtest-internal.h