otus_cpp_print_ip: testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator Class Reference
testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator Class Reference
Public Member Functions
Iterator (const ParamGeneratorInterface< T > *base, typename ContainerType::const_iterator iterator)
~Iterator () override
const ParamGeneratorInterface< T > * BaseGenerator () const override
void Advance () override
ParamIteratorInterface< T > * Clone () const override
const T * Current () const override
bool Equals (const ParamIteratorInterface< T > &other) const override
Public Member Functions inherited from testing::internal::ParamIteratorInterface< T >
virtual ~ParamIteratorInterface ()
Private Member Functions
Iterator (const Iterator &other)
Private Attributes
const ParamGeneratorInterface< T > *const base_
ContainerType::const_iterator iterator_
std::unique_ptr< const T > value_
Detailed Description
template<typename T>
class testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator
Definition at line 309 of file gtest-param-util.h.
Constructor & Destructor Documentation
Iterator() [1/2]
template<typename T > testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Iterator (const ParamGeneratorInterface< T > * base, typename ContainerType::const_iterator iterator) inline
Definition at line 311 of file gtest-param-util.h.
         : base_(base), iterator_(iterator) {}
Referenced by testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Clone().
~Iterator()
template<typename T > testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::~Iterator () inline override
Definition at line 314 of file gtest-param-util.h.
 {}
Iterator() [2/2]
template<typename T > testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Iterator (const Iterator & other) inline private
Definition at line 348 of file gtest-param-util.h.
         : ParamIteratorInterface<T>(),
           base_(other.base_),
           iterator_(other.iterator_) {}
Member Function Documentation
Advance()
template<typename T > void testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Advance () inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 319 of file gtest-param-util.h.
{
       ++iterator_;
       value_.reset();
     }
References testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::iterator_, and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::value_.
BaseGenerator()
template<typename T > const ParamGeneratorInterface<T>* testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::BaseGenerator () const inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 316 of file gtest-param-util.h.
{
       return base_;
     }
References testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::base_.
Referenced by testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Equals().
Clone()
template<typename T > ParamIteratorInterface<T>* testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Clone () const inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 323 of file gtest-param-util.h.
{
       return new Iterator(*this);
     }
References testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Iterator().
Current()
template<typename T > const T* testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Current () const inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 333 of file gtest-param-util.h.
{
       if (value_.get() == nullptr) value_.reset(new T(*iterator_));
       return value_.get();
     }
References testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::iterator_, and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::value_.
Equals()
template<typename T > bool testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Equals (const ParamIteratorInterface< T > & other) const inline override virtual
Implements testing::internal::ParamIteratorInterface< T >.
Definition at line 337 of file gtest-param-util.h.
{
       // Having the same base generator guarantees that the other
       // iterator is of the same type and we can downcast.
       GTEST_CHECK_(BaseGenerator() == other.BaseGenerator())
           << "The program attempted to compare iterators "
           << "from different generators." << std::endl;
       return iterator_ ==
           CheckedDowncastToActualType<const Iterator>(&other)->iterator_;
     }
References testing::internal::ParamIteratorInterface< T >::BaseGenerator(), testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::BaseGenerator(), GTEST_CHECK_, and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::iterator_.
Member Data Documentation
base_
template<typename T > const ParamGeneratorInterface<T>* const testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::base_ private
Definition at line 355 of file gtest-param-util.h.
Referenced by testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::BaseGenerator().
iterator_
template<typename T > ContainerType::const_iterator testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::iterator_ private
Definition at line 356 of file gtest-param-util.h.
Referenced by testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Advance(), testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Current(), and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Equals().
value_
template<typename T > std::unique_ptr<const T> testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::value_ mutable private
Definition at line 362 of file gtest-param-util.h.
Referenced by testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Advance(), and testing::internal::ValuesInIteratorRangeGenerator< T >::Iterator::Current().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/internal/gtest-param-util.h