otus_cpp_print_ip: testing::internal::UniversalTersePrinter< T > Class Template Reference
testing::internal::UniversalTersePrinter< T > Class Template Reference
#include <gtest-printers.h>
Static Public Member Functions
static void Print (const T &value, ::std::ostream *os)
Detailed Description
template<typename T>
class testing::internal::UniversalTersePrinter< T >
Definition at line 831 of file gtest-printers.h.
Member Function Documentation
Print()
template<typename T > static void testing::internal::UniversalTersePrinter< T >::Print (const T & value, ::std::ostream * os) inline static
Definition at line 833 of file gtest-printers.h.
{
     UniversalPrint(value, os);
   }
References testing::internal::UniversalPrint().
Referenced by testing::internal::UniversalTersePrinter< char * >::Print(), testing::internal::UniversalTersePrinter< wchar_t * >::Print(), testing::PrintToString(), and testing::internal::UniversalTersePrint().
The documentation for this class was generated from the following file:
_deps/googletest-src/googletest/include/gtest/gtest-printers.h