name: 'Deploy docs on github pages'

on:
  push:
    branches:
      - main
      - dev

jobs:
  
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sed -i 's/MY_PROJECT_VERSION/0.0.${{ github.run_number }}/' print_ip.cpp

      - run: sed -i 's/MY_PROJECT_VERSION/0.0.${{ github.run_number }}/' Doxyfile
      - run: cat Doxyfile
      - run: mkdir docs; cd docs; mkdir html;
      - run: touch docs/html/.nojekyll
      - run: sudo apt-get install doxygen -y
      - run: doxygen Doxyfile
      - run: ls -aq 
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/html

      

      

      
