name: 'C++ CI'

on:
  push:
    branches:
      - main
      - dev

jobs:
  
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build . --target print_ip 
      - run: cmake --build . --target test_print_ip
      - run: tests/test_print_ip
      - run: ./print_ip
      - run: cpack
      - run: dpkg -c print_ip-0.0.${{ github.run_number }}-Linux.deb

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./print_ip-0.0.${{ github.run_number }}-Linux.deb
          asset_name: print_ip-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

      - run: sed -i 's/MY_PROJECT_VERSION/0.0.${{ github.run_number }}/' Doxyfile
      - run: cat Doxyfile
      - run: touch docs/html/.nojekyll 
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy.

      # - uses: DenverCoder1/doxygen-github-pages-action@v1.1.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: gh-pages
      #     folder: docs/html
      #     config_file: myDoxyfile





      

      

      
